# Base de Datos: Nogoyá #

### Lectura de datos ## 

In [1]:
# Ruta donde se guarda el archivo Excel
ruta_guardado <- "C:/Users/guill/OneDrive/Escritorio/NOGOYÁ.csv"
# Lee el archivo CSV con read_csv()
NOGOYA <- read.csv(ruta_guardado)
#options(repr.matrix.max.rows=Inf, repr.matrix.max.cols=Inf)
NOGOYA

X      CUE     departamento localidad CodigoPostal EsPrivada turno   
1       1     9003450 NOGOYA       NOGOYÁ    3150         N         MAÑANA  
2       2     9003450 NOGOYA       NOGOYÁ    3150         N         MAÑANA  
3       3     9003450 NOGOYA       NOGOYÁ    3150         N         MAÑANA  
4       4     9003450 NOGOYA       NOGOYÁ    3150         N         MAÑANA  
5       5     9003450 NOGOYA       NOGOYÁ    3150         N         MAÑANA  
6       6     9003450 NOGOYA       NOGOYÁ    3150         N         MAÑANA  
7       7     9003450 NOGOYA       NOGOYÁ    3150         N         MAÑANA  
8       8     9003450 NOGOYA       NOGOYÁ    3150         N         MAÑANA  
9       9     9003450 NOGOYA       NOGOYÁ    3150         N         MAÑANA  
10     10     9003450 NOGOYA       NOGOYÁ    3150         N         MAÑANA  
11     11     9003450 NOGOYA       NOGOYÁ    3150         N         MAÑANA  
12     12     9003450 NOGOYA       NOGOYÁ    3150         N         MAÑANA  
13     13     9005721 NOGOYA       NOGOYÁ    3177         N         TARDE   
14     14     9005721 NOGOYA       NOGOYÁ    3177         N         TARDE   
15     15     9005721 NOGOYA       NOGOYÁ    3177         N         TARDE   
16     16     9005721 NOGOYA       NOGOYÁ    3177         N         TARDE   
17     17     9005721 NOGOYA       NOGOYÁ    3177         N         TARDE   
18     18     9005721 NOGOYA       NOGOYÁ    3177         N         TARDE   
19     19     9005721 NOGOYA       NOGOYÁ    3177         N         TARDE   
20     20     9005721 NOGOYA       NOGOYÁ    3177         N         TARDE   
21     21     9005721 NOGOYA       NOGOYÁ    3177         N         TARDE   
22     22     9005721 NOGOYA       NOGOYÁ    3177         N         TARDE   
23     23     9005721 NOGOYA       NOGOYÁ    3177         N         TARDE   
24     24     9005721 NOGOYA       NOGOYÁ    3177         N         TARDE   
25     25     9002271 NOGOYA       NOGOYÁ    3164         N         ROTATIVO
26     26     9002271 NOGOYA       NOGOYÁ    3164         N         ROTATIVO
27     27     9002271 NOGOYA       NOGOYÁ    3164         N         ROTATIVO
28     28     9002271 NOGOYA       NOGOYÁ    3164         N         ROTATIVO
29     29     9002271 NOGOYA       NOGOYÁ    3164         N         ROTATIVO
30     30     9002271 NOGOYA       NOGOYÁ    3164         N         ROTATIVO
...    ...    ...     ...          ...       ...          ...       ...     
326592 326592 9007683 NOGOYA       NOGOYÁ    3158         N         MAÑANA  
326593 326593 9007683 NOGOYA       NOGOYÁ    3158         N         MAÑANA  
326594 326594 9007683 NOGOYA       NOGOYÁ    3158         N         MAÑANA  
326595 326595 9007683 NOGOYA       NOGOYÁ    3158         N         MAÑANA  
326596 326596 9007683 NOGOYA       NOGOYÁ    3158         N         MAÑANA  
326597 326597 9007683 NOGOYA       NOGOYÁ    3158         N         MAÑANA  
326598 326598 9007683 NOGOYA       NOGOYÁ    3158         N         MAÑANA  
326599 326599 9007683 NOGOYA       NOGOYÁ    3158         N         MAÑANA  
326600 326600 9007683 NOGOYA       NOGOYÁ    3158         N         MAÑANA  
326601 326601 9007683 NOGOYA       NOGOYÁ    3158         N         MAÑANA  
326602 326602 9007683 NOGOYA       NOGOYÁ    3158         N         MAÑANA  
326603 326603 9007683 NOGOYA       NOGOYÁ    3158         N         MAÑANA  
326604 326604 9007683 NOGOYA       NOGOYÁ    3158         N         MAÑANA  
326605 326605 9007683 NOGOYA       NOGOYÁ    3158         N         MAÑANA  
326606 326606 9007683 NOGOYA       NOGOYÁ    3158         N         MAÑANA  
326607 326607 9007683 NOGOYA       NOGOYÁ    3158         N         MAÑANA  
326608 326608 9007683 NOGOYA       NOGOYÁ    3158         N         MAÑANA  
326609 326609 9007683 NOGOYA       NOGOYÁ    3158         N         MAÑANA  
326610 326610 9007683 NOGOYA       NOGOYÁ    3158         N         MAÑANA  
326611 326611 9007683 NOGOYA       NOGOYÁ    3158         N         MAÑANA  
326

### Exploración de Datos

In [2]:
#tamaño
dim(NOGOYA)
#Cantidad de columnas
length(NOGOYA) 
#Cantidad de filas
nrow(NOGOYA) 

[1] 326621     26

[1] 26

[1] 326621

El tamaño del dataset es de 326621 filas por 26 columnas

In [3]:
#Nombre de las columnas
names(NOGOYA)
#Muestra la declaracion de las variables
str(NOGOYA) 

[1] "X"                  "CUE"                "departamento"      
 [4] "localidad"          "CodigoPostal"       "EsPrivada"         
 [7] "turno"              "curso"              "periodoEvaluatorio"
[10] "idalumno"           "Documento"          "anioLectivo"       
[13] "asignatura"         "nota"               "observaciones"     
[16] "idSubOrganizacion"  "idDivision"         "NivelEnsenanza"    
[19] "orden"              "idOrganizaciones"   "ddivision"         
[22] "Nivel"              "esMultianio"        "IdModEnsenanza"    
[25] "Modalidad"          "ModEnsenaza"

'data.frame':	326621 obs. of  26 variables:
 $ X                 : int  1 2 3 4 5 6 7 8 9 10 ...
 $ CUE               : int  9003450 9003450 9003450 9003450 9003450 9003450 9003450 9003450 9003450 9003450 ...
 $ departamento      : chr  "NOGOYA" "NOGOYA" "NOGOYA" "NOGOYA" ...
 $ localidad         : chr  "NOGOYÁ" "NOGOYÁ" "NOGOYÁ" "NOGOYÁ" ...
 $ CodigoPostal      : int  3150 3150 3150 3150 3150 3150 3150 3150 3150 3150 ...
 $ EsPrivada         : chr  "N" "N" "N" "N" ...
 $ turno             : chr  "MAÑANA" "MAÑANA" "MAÑANA" "MAÑANA" ...
 $ curso             : chr  "4 - C Prim" "4 - C Prim" "4 - C Prim" "4 - C Prim" ...
 $ periodoEvaluatorio: chr  "Primer Trimestre" "Primer Trimestre" "Primer Trimestre" "Primer Trimestre" ...
 $ idalumno          : int  661799 661799 661799 661799 661799 661799 661799 661799 661799 661799 ...
 $ Documento         : int  53810103 53810103 53810103 53810103 53810103 53810103 53810103 53810103 53810103 53810103 ...
 $ anioLectivo       : int  2023 2023 202

In [4]:
#filtrar
table(NOGOYA$Modalidad,NOGOYA$curso)

                   
                    1-2-3 - A Prim 1-2 - A Prim 1-3 - A Prim 1-3 - U Prim
  Inicial                       96          113          294           24
  NULL                           0            0           81            0
  Primaria                     192          516          806          128
  Primaria 3 ciclos              0            0            0            0
  Secundaria                     0            0            0            0
  Secundaria 3 años              0            0            0            0
                   
                    1-6 - A Prim 1 - 1 RCBCET 1 - 1 RCBEAT 1 - 2 RCBCET
  Inicial                    383           42           43            0
  NULL                       165           82          214           41
  Primaria                  4658          965          175          559
  Primaria 3 ciclos            0            0            0            0
  Secundaria                   0          936         2190          747
  Secundar

In [5]:
table(NOGOYA$NivelEnsenanza)


  PRIMARIO SECUNDARIO 
    148691     177930 

In [6]:
table(NOGOYA$ModEnsenaza)


              Adultos           Agrotécnica      Cap Tecnica Priv 
                14980                 17594                   137 
                Comun           Ed.Especial         Escuelas NINA 
               280885                  1322                    89 
Formacion Profesional               Técnica 
                  193                 11421 

In [7]:
#Variables con NA
variables_con_na <- colSums(is.na(NOGOYA)) > 0
na_por_variable <- colSums(is.na(NOGOYA))

# Muestra las variables con NA
print("Variables con NA: ")
print(names(variables_con_na[variables_con_na]))
print("Cantidad de NA: ")
print(na_por_variable)


[1] "Variables con NA: "
[1] "asignatura"    "observaciones"
[1] "Cantidad de NA: "
                 X                CUE       departamento          localidad 
                 0                  0                  0                  0 
      CodigoPostal          EsPrivada              turno              curso 
                 0                  0                  0                  0 
periodoEvaluatorio           idalumno          Documento        anioLectivo 
                 0                  0                  0                  0 
        asignatura               nota      observaciones  idSubOrganizacion 
               109                  0             324414                  0 
        idDivision     NivelEnsenanza              orden   idOrganizaciones 
                 0                  0                  0                  0 
         ddivision              Nivel        esMultianio     IdModEnsenanza 
                 0                  0                  0             

In [8]:
# Ver cuántos valores "NULL" (como texto) hay en cada columna de tipo character
null_en_chr <- sapply(NOGOYA, function(col) sum(col == "NULL", na.rm = TRUE))

# Mostrar solo las variables donde hay "NULL"
print("Variables de tipo character que contienen 'NULL' como string:")
print(names(null_en_chr[null_en_chr > 0]))

# Mostrar la cantidad de "NULL" encontrados en cada una
print("Cantidad de 'NULL' como string por variable:")
print(null_en_chr[null_en_chr > 0])



[1] "Variables de tipo character que contienen 'NULL' como string:"
[1] "nota"      "Modalidad"
[1] "Cantidad de 'NULL' como string por variable:"
     nota Modalidad 
     5767     23512 


Se puede observar que las variables que poseen NA son asignatura y observaciones, con 109 y 324414 datos NA, respectivamente. Sin embargo, existen dos variables que contienen valores NULL, Nota y Modalidad.

In [9]:
names(NOGOYA)

[1] "X"                  "CUE"                "departamento"      
 [4] "localidad"          "CodigoPostal"       "EsPrivada"         
 [7] "turno"              "curso"              "periodoEvaluatorio"
[10] "idalumno"           "Documento"          "anioLectivo"       
[13] "asignatura"         "nota"               "observaciones"     
[16] "idSubOrganizacion"  "idDivision"         "NivelEnsenanza"    
[19] "orden"              "idOrganizaciones"   "ddivision"         
[22] "Nivel"              "esMultianio"        "IdModEnsenanza"    
[25] "Modalidad"          "ModEnsenaza"

## Arreglo de datos ##

In [10]:
library (dplyr)
# renombrar variables
NOGOYA <- rename(NOGOYA,  
         Departamento = departamento, 
         Localidad = localidad, 
         CP = CodigoPostal, 
         EsPrivada = EsPrivada, 
         Turno = turno, 
         Curso = curso, 
         PeriodoEvaluatorio = periodoEvaluatorio, 
         IDalumno = idalumno, 
         Documento = Documento, 
         AnioLectivo = anioLectivo, 
         Asignatura = asignatura, 
         Nota = nota, 
         Observaciones = observaciones, 
         IDSubOrganizacion = idSubOrganizacion, 
         IDDivision = idDivision, 
         NivelEnsenanza = NivelEnsenanza, 
         Orden = orden, 
         IDOrganizaciones = idOrganizaciones, 
         Division = ddivision, 
         Nivel = Nivel, 
         EsMultianio = esMultianio, 
         IDModEnsenanza = IdModEnsenanza, 
         Modalidad = Modalidad, 
         ModEnsenanza = ModEnsenaza)

names(NOGOYA)




Attaching package: 'dplyr'


The following objects are masked from 'package:stats':

    filter, lag


The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union




[1] "X"                  "CUE"                "Departamento"      
 [4] "Localidad"          "CP"                 "EsPrivada"         
 [7] "Turno"              "Curso"              "PeriodoEvaluatorio"
[10] "IDalumno"           "Documento"          "AnioLectivo"       
[13] "Asignatura"         "Nota"               "Observaciones"     
[16] "IDSubOrganizacion"  "IDDivision"         "NivelEnsenanza"    
[19] "Orden"              "IDOrganizaciones"   "Division"          
[22] "Nivel"              "EsMultianio"        "IDModEnsenanza"    
[25] "Modalidad"          "ModEnsenanza"

In [11]:
glimpse(NOGOYA)

Rows: 326,621
Columns: 26
$ X                  <int> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, ~
$ CUE                <int> 9003450, 9003450, 9003450, 9003450, 9003450, 900345~
$ Departamento       <chr> "NOGOYA", "NOGOYA", "NOGOYA", "NOGOYA", "NOGOYA", "~
$ Localidad          <chr> "NOGOYÁ", "NOGOYÁ", "NOGOYÁ", "NOGOYÁ", "NOGOYÁ", "~
$ CP                 <int> 3150, 3150, 3150, 3150, 3150, 3150, 3150, 3150, 315~
$ EsPrivada          <chr> "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "~
$ Turno              <chr> "MAÑANA", "MAÑANA", "MAÑANA", "MAÑANA", "MAÑANA", "~
$ Curso              <chr> "4 - C Prim", "4 - C Prim", "4 - C Prim", "4 - C Pr~
$ PeriodoEvaluatorio <chr> "Primer Trimestre", "Primer Trimestre", "Primer Tri~
$ IDalumno           <int> 661799, 661799, 661799, 661799, 661799, 661799, 661~
$ Documento          <int> 53810103, 53810103, 53810103, 53810103, 53810103, 5~
$ AnioLectivo        <int> 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 202~
$ Asignatura  

In [12]:
library(dplyr)

NOGOYA <- NOGOYA %>% select(-c(IDDivision, Orden, IDalumno, Observaciones, 
                               IDSubOrganizacion, IDOrganizaciones, 
                               IDModEnsenanza, Modalidad, Nivel))


In [13]:
head (NOGOYA)

X CUE     Departamento Localidad CP   EsPrivada Turno  Curso     
1 1 9003450 NOGOYA       NOGOYÁ    3150 N         MAÑANA 4 - C Prim
2 2 9003450 NOGOYA       NOGOYÁ    3150 N         MAÑANA 4 - C Prim
3 3 9003450 NOGOYA       NOGOYÁ    3150 N         MAÑANA 4 - C Prim
4 4 9003450 NOGOYA       NOGOYÁ    3150 N         MAÑANA 4 - C Prim
5 5 9003450 NOGOYA       NOGOYÁ    3150 N         MAÑANA 4 - C Prim
6 6 9003450 NOGOYA       NOGOYÁ    3150 N         MAÑANA 4 - C Prim
  PeriodoEvaluatorio Documento AnioLectivo Asignatura                        
1 Primer Trimestre   53810103  2023        EDUCACION MUSICAL                 
2 Primer Trimestre   53810103  2023        Taller de Educación del Movimiento
3 Primer Trimestre   53810103  2023        Taller de Inglés                  
4 Primer Trimestre   53810103  2023        MATEMATICA                        
5 Primer Trimestre   53810103  2023        CIENCIAS NATURALES                
6 Primer Trimestre   53810103  2023        CIENCIAS SOCIALES                 
  Nota NivelEnsenanza Division EsMultianio ModEnsenanza
1 7    PRIMARIO       68567    N           Comun       
2 8    PRIMARIO       68567    N           Comun       
3 7    PRIMARIO       68567    N           Comun       
4 EPAC PRIMARIO       68567    N           Comun       
5 6    PRIMARIO       68567    N           Comun       
6 6    PRIMARIO       68567    N           Comun

## Dataset Escuelas Primarias ##


In [14]:
#filtrar datos y generar nuevo dataset para las escuelas primarias
dim(NOGOYA)

NOGOYAP <-filter(NOGOYA,  NivelEnsenanza=="PRIMARIO" & EsMultianio== "N" &  ModEnsenanza=="Comun")

dim(NOGOYAP)
NOGOYAP

[1] 326621     17

[1] 126333     17

X      CUE     Departamento Localidad CP   EsPrivada Turno  Curso     
1        1    9003450 NOGOYA       NOGOYÁ    3150 N         MAÑANA 4 - C Prim
2        2    9003450 NOGOYA       NOGOYÁ    3150 N         MAÑANA 4 - C Prim
3        3    9003450 NOGOYA       NOGOYÁ    3150 N         MAÑANA 4 - C Prim
4        4    9003450 NOGOYA       NOGOYÁ    3150 N         MAÑANA 4 - C Prim
5        5    9003450 NOGOYA       NOGOYÁ    3150 N         MAÑANA 4 - C Prim
6        6    9003450 NOGOYA       NOGOYÁ    3150 N         MAÑANA 4 - C Prim
7        7    9003450 NOGOYA       NOGOYÁ    3150 N         MAÑANA 4 - C Prim
8        8    9003450 NOGOYA       NOGOYÁ    3150 N         MAÑANA 4 - C Prim
9        9    9003450 NOGOYA       NOGOYÁ    3150 N         MAÑANA 4 - C Prim
10      10    9003450 NOGOYA       NOGOYÁ    3150 N         MAÑANA 4 - C Prim
11      11    9003450 NOGOYA       NOGOYÁ    3150 N         MAÑANA 4 - C Prim
12      12    9003450 NOGOYA       NOGOYÁ    3150 N         MAÑANA 4 - C Prim
13     109    9005373 NOGOYA       NOGOYÁ    3158 N         TARDE  1 - A Prim
14     110    9005373 NOGOYA       NOGOYÁ    3158 N         TARDE  1 - A Prim
15     111    9005373 NOGOYA       NOGOYÁ    3158 N         TARDE  1 - A Prim
16     112    9005373 NOGOYA       NOGOYÁ    3158 N         TARDE  1 - A Prim
17     113    9005373 NOGOYA       NOGOYÁ    3158 N         TARDE  1 - A Prim
18     114    9005373 NOGOYA       NOGOYÁ    3158 N         TARDE  1 - A Prim
19     115    9005373 NOGOYA       NOGOYÁ    3158 N         TARDE  1 - A Prim
20     116    9005373 NOGOYA       NOGOYÁ    3158 N         TARDE  1 - A Prim
21     117    9005373 NOGOYA       NOGOYÁ    3158 N         TARDE  1 - A Prim
22     118    9005373 NOGOYA       NOGOYÁ    3158 N         TARDE  1 - A Prim
23     119    9005373 NOGOYA       NOGOYÁ    3158 N         TARDE  1 - A Prim
24     120    9005373 NOGOYA       NOGOYÁ    3158 N         TARDE  1 - A Prim
25     133    9005373 NOGOYA       NOGOYÁ    3158 N         TARDE  1 - A Prim
26     134    9005373 NOGOYA       NOGOYÁ    3158 N         TARDE  1 - A Prim
27     135    9005373 NOGOYA       NOGOYÁ    3158 N         TARDE  1 - A Prim
28     136    9005373 NOGOYA       NOGOYÁ    3158 N         TARDE  1 - A Prim
29     137    9005373 NOGOYA       NOGOYÁ    3158 N         TARDE  1 - A Prim
30     138    9005373 NOGOYA       NOGOYÁ    3158 N         TARDE  1 - A Prim
...    ...    ...     ...          ...       ...  ...       ...    ...       
126304 148662 9027069 NOGOYA       NOGOYÁ    3150 S         TARDE  6 - A Prim
126305 148663 9027069 NOGOYA       NOGOYÁ    3150 S         TARDE  6 - A Prim
126306 148664 9027069 NOGOYA       NOGOYÁ    3150 S         TARDE  6 - A Prim
126307 148665 9027069 NOGOYA       NOGOYÁ    3150 S         TARDE  6 - A Prim
126308 148666 9027069 NOGOYA       NOGOYÁ    3150 S         TARDE  6 - A Prim
126309 148667 9027069 NOGOYA       NOGOYÁ    3150 S         TARDE  6 - A Prim
126310 148668 9027069 NOGOYA       NOGOYÁ    3150 S         TARDE  6 - A Prim
126311 148669 9027069 NOGOYA       NOGOYÁ    3150 S         TARDE  6 - A Prim
126312 148670 9027069 NOGOYA       NOGOYÁ    3150 S         TARDE  6 - B Prim
126313 148671 9027069 NOGOYA       NOGOYÁ    3150 S         TARDE  6 - B Prim
126314 148672 9027069 NOGOYA       NOGOYÁ    3150 S         TARDE  6 - B Prim
126315 148673 9027069 NOGOYA       NOGOYÁ    3150 S         TARDE  6 - B Prim
126316 148674 9027069 NOGOYA       NOGOYÁ    3150 S         TARDE  6 - B Prim
126317 148675 9027069 NOGOYA       NOGOYÁ    3150 S         TARDE  6 - B Prim
126318 148676 9027069 NOGOYA       NOGOYÁ    3150 S         TARDE  6 - B Prim
126319 148677 9027069 NOGOYA       NOGOYÁ    3150 S         TARDE  6 - B Prim
126320 148678 9027069 NOGOYA       NOGOYÁ    3150 S         TARDE  6 - B Prim
126321 148679 9027069 NOGOYA       NOGOYÁ    3150 S         TARDE  6 - B Prim
126322 148680 9027069 NOGOYA       NOGOYÁ    3150 S         TARDE  6 - B Prim
126323 148681 9027069 NOGOYA 

In [15]:
table(NOGOYAP$Turno)


COMPLETO   DIURNO    DOBLE   MAÑANA ROTATIVO    TARDE 
    3556       24       72    54639      779    67263 

In [16]:
# Contar el número total de códigos únicos (escuelas)
num_total_escuelas_p <- NOGOYAP %>%
  summarise(num_total_escuelas_p = n_distinct(CUE))

# Mostrar el resultado
print(num_total_escuelas_p)

  num_total_escuelas_p
1                   46


### Procesamiento de la variable Curso ###

In [17]:
table(NOGOYAP$Curso)


         1-2 - A Prim          1-3 - A Prim          1-6 - A Prim 
                   40                    55                   309 
       1 - 6 - A Prim            1 - A Prim            1 - B Prim 
                   15                  9533                  5441 
           1 - C Prim            1 - D Prim        1 a 3 - A Prim 
                 1224                   361                    48 
1° , 2° Y 3° - A Prim  1°, 2° y 3° - A Prim      1º - 6º - A Prim 
                   48                    24                    16 
        1y 2 - A Prim            2 - A Prim            2 - B Prim 
                    2                  9232                  6547 
           2 - C Prim            2 - D Prim            2 - U Prim 
                 1944                   428                    72 
       2 y 3 - A Prim     3- 4-5-6 - A Prim          3-4 - A Prim 
                   72                    32                    18 
           3 - A Prim            3 - B Prim            3 - C 

In [18]:
NOGOYAP2 <-filter(NOGOYAP, !grepl("y", Curso) & !grepl("Y", Curso) & !grepl("a", Curso) & !grepl("°", Curso) & !grepl(",", Curso) & !grepl("º", Curso))
table(NOGOYAP2$Curso)


     1-2 - A Prim      1-3 - A Prim      1-6 - A Prim    1 - 6 - A Prim 
               40                55               309                15 
       1 - A Prim        1 - B Prim        1 - C Prim        1 - D Prim 
             9533              5441              1224               361 
       2 - A Prim        2 - B Prim        2 - C Prim        2 - D Prim 
             9232              6547              1944               428 
       2 - U Prim 3- 4-5-6 - A Prim      3-4 - A Prim        3 - A Prim 
               72                32                18             10791 
       3 - B Prim        3 - C Prim        3 - D Prim        3 - U Prim 
             6670              1192               361                24 
   4-5-6 - A Prim      4-6 - A Prim        4 - A Prim        4 - B Prim 
                8                46             12638              8022 
       4 - B PRIM        4 - C Prim        4 - U Prim        5 - A Prim 
              160              2041               

In [19]:
NOGOYAP3 <-filter(NOGOYAP2, !grepl("4-5-6 - A Prim", Curso) & !grepl("3- 4-5-6 - A Prim", Curso) & !grepl("1 - 6 - A Prim", Curso))
table(NOGOYAP3$Curso)


1-2 - A Prim 1-3 - A Prim 1-6 - A Prim   1 - A Prim   1 - B Prim   1 - C Prim 
          40           55          309         9533         5441         1224 
  1 - D Prim   2 - A Prim   2 - B Prim   2 - C Prim   2 - D Prim   2 - U Prim 
         361         9232         6547         1944          428           72 
3-4 - A Prim   3 - A Prim   3 - B Prim   3 - C Prim   3 - D Prim   3 - U Prim 
          18        10791         6670         1192          361           24 
4-6 - A Prim   4 - A Prim   4 - B Prim   4 - B PRIM   4 - C Prim   4 - U Prim 
          46        12638         8022          160         2041           24 
  5 - A Prim   5 - B Prim   5 - C Prim   5 - D Prim   5 - U Prim   6 - A Prim 
       12948         9975         1562          576           23        13358 
  6 - B Prim   6 - C Prim   6 - U Prim 
        8365         1193          565 

In [20]:
NOGOYAP3$Curso <- substr(NOGOYAP3$Curso, 1, 1)
table(NOGOYAP3$Curso)


    1     2     3     4     5     6 
16963 18223 19056 22931 25084 23481 

### Total de alumnos ###

In [21]:
# Contar el número total de documentos únicos (alumnos)
num_total_alumnos_p <- NOGOYAP3 %>%
  summarise(num_total_alumnos_p = n_distinct(Documento))

# Mostrar el resultado
print(num_total_alumnos_p)

  num_total_alumnos_p
1                3460


### Separacion por Trimestre ###

In [22]:
PrimerTPrimario<-filter(NOGOYAP3,PeriodoEvaluatorio=="Primer Trimestre")
head(PrimerTPrimario)
names(PrimerTPrimario)
PrimerTPrimario<-rename(PrimerTPrimario,NotasPrimerTPrimario=Nota)
dim(PrimerTPrimario)
names(PrimerTPrimario)

X CUE     Departamento Localidad CP   EsPrivada Turno  Curso
1 1 9003450 NOGOYA       NOGOYÁ    3150 N         MAÑANA 4    
2 2 9003450 NOGOYA       NOGOYÁ    3150 N         MAÑANA 4    
3 3 9003450 NOGOYA       NOGOYÁ    3150 N         MAÑANA 4    
4 4 9003450 NOGOYA       NOGOYÁ    3150 N         MAÑANA 4    
5 5 9003450 NOGOYA       NOGOYÁ    3150 N         MAÑANA 4    
6 6 9003450 NOGOYA       NOGOYÁ    3150 N         MAÑANA 4    
  PeriodoEvaluatorio Documento AnioLectivo Asignatura                        
1 Primer Trimestre   53810103  2023        EDUCACION MUSICAL                 
2 Primer Trimestre   53810103  2023        Taller de Educación del Movimiento
3 Primer Trimestre   53810103  2023        Taller de Inglés                  
4 Primer Trimestre   53810103  2023        MATEMATICA                        
5 Primer Trimestre   53810103  2023        CIENCIAS NATURALES                
6 Primer Trimestre   53810103  2023        CIENCIAS SOCIALES                 
  Nota NivelEnsenanza Division EsMultianio ModEnsenanza
1 7    PRIMARIO       68567    N           Comun       
2 8    PRIMARIO       68567    N           Comun       
3 7    PRIMARIO       68567    N           Comun       
4 EPAC PRIMARIO       68567    N           Comun       
5 6    PRIMARIO       68567    N           Comun       
6 6    PRIMARIO       68567    N           Comun

[1] "X"                  "CUE"                "Departamento"      
 [4] "Localidad"          "CP"                 "EsPrivada"         
 [7] "Turno"              "Curso"              "PeriodoEvaluatorio"
[10] "Documento"          "AnioLectivo"        "Asignatura"        
[13] "Nota"               "NivelEnsenanza"     "Division"          
[16] "EsMultianio"        "ModEnsenanza"

[1] 40726    17

[1] "X"                    "CUE"                  "Departamento"        
 [4] "Localidad"            "CP"                   "EsPrivada"           
 [7] "Turno"                "Curso"                "PeriodoEvaluatorio"  
[10] "Documento"            "AnioLectivo"          "Asignatura"          
[13] "NotasPrimerTPrimario" "NivelEnsenanza"       "Division"            
[16] "EsMultianio"          "ModEnsenanza"

In [23]:
SegundoTPrimario<-filter(NOGOYAP3,PeriodoEvaluatorio=="Segundo Trimestre")
head(SegundoTPrimario)
names(SegundoTPrimario)
SegundoTPrimario<-rename(SegundoTPrimario,NotasSegundoTPrimario=Nota)
dim(SegundoTPrimario)
names(SegundoTPrimario)

X    CUE     Departamento Localidad CP   EsPrivada Turno  Curso
1  642 9000303 NOGOYA       NOGOYÁ    3150 N         MAÑANA 5    
2 1101 9000303 NOGOYA       NOGOYÁ    3150 N         MAÑANA 5    
3 1124 9000303 NOGOYA       NOGOYÁ    3150 N         MAÑANA 5    
4 1127 9000303 NOGOYA       NOGOYÁ    3150 N         MAÑANA 5    
5 1460 9000303 NOGOYA       NOGOYÁ    3150 N         MAÑANA 5    
6 1467 9000303 NOGOYA       NOGOYÁ    3150 N         MAÑANA 5    
  PeriodoEvaluatorio Documento AnioLectivo Asignatura            Nota
1 Segundo Trimestre  52260341  2023        EDUCACION TECNOLOGICA NULL
2 Segundo Trimestre  52821102  2023        EDUCACION TECNOLOGICA NULL
3 Segundo Trimestre  53004186  2023        EDUCACION TECNOLOGICA NULL
4 Segundo Trimestre  52730645  2023        EDUCACION TECNOLOGICA NULL
5 Segundo Trimestre  52493195  2023        EDUCACION TECNOLOGICA NULL
6 Segundo Trimestre  52946932  2023        EDUCACION TECNOLOGICA NULL
  NivelEnsenanza Division EsMultianio ModEnsenanza
1 PRIMARIO       66998    N           Comun       
2 PRIMARIO       66998    N           Comun       
3 PRIMARIO       66998    N           Comun       
4 PRIMARIO       66998    N           Comun       
5 PRIMARIO       66998    N           Comun       
6 PRIMARIO       66998    N           Comun

[1] "X"                  "CUE"                "Departamento"      
 [4] "Localidad"          "CP"                 "EsPrivada"         
 [7] "Turno"              "Curso"              "PeriodoEvaluatorio"
[10] "Documento"          "AnioLectivo"        "Asignatura"        
[13] "Nota"               "NivelEnsenanza"     "Division"          
[16] "EsMultianio"        "ModEnsenanza"

[1] 41536    17

[1] "X"                     "CUE"                   "Departamento"         
 [4] "Localidad"             "CP"                    "EsPrivada"            
 [7] "Turno"                 "Curso"                 "PeriodoEvaluatorio"   
[10] "Documento"             "AnioLectivo"           "Asignatura"           
[13] "NotasSegundoTPrimario" "NivelEnsenanza"        "Division"             
[16] "EsMultianio"           "ModEnsenanza"

In [24]:
TercerTPrimario<-filter(NOGOYAP3,PeriodoEvaluatorio=="Tercer Trimestre")
head(TercerTPrimario)
names(TercerTPrimario)
TercerTPrimario<-rename(TercerTPrimario,NotasTercerTPrimario=Nota)
dim(TercerTPrimario)
names(TercerTPrimario)

X    CUE     Departamento Localidad CP   EsPrivada Turno Curso
1 4626 9003450 NOGOYA       NOGOYÁ    3150 N         TARDE 1    
2 4646 9003450 NOGOYA       NOGOYÁ    3150 N         TARDE 1    
3 4647 9003450 NOGOYA       NOGOYÁ    3150 N         TARDE 1    
4 4649 9003450 NOGOYA       NOGOYÁ    3150 N         TARDE 1    
5 4653 9003450 NOGOYA       NOGOYÁ    3150 N         TARDE 1    
6 4655 9003450 NOGOYA       NOGOYÁ    3150 N         TARDE 1    
  PeriodoEvaluatorio Documento AnioLectivo Asignatura         Nota
1 Tercer Trimestre   55860361  2023        LENGUA             9   
2 Tercer Trimestre   55860361  2023        MATEMATICA         9   
3 Tercer Trimestre   55860361  2023        CIENCIAS NATURALES 9   
4 Tercer Trimestre   55860361  2023        CIENCIAS SOCIALES  9   
5 Tercer Trimestre   55860311  2023        LENGUA             8   
6 Tercer Trimestre   55860311  2023        CIENCIAS NATURALES 8   
  NivelEnsenanza Division EsMultianio ModEnsenanza
1 PRIMARIO       68555    N           Comun       
2 PRIMARIO       68555    N           Comun       
3 PRIMARIO       68555    N           Comun       
4 PRIMARIO       68555    N           Comun       
5 PRIMARIO       68555    N           Comun       
6 PRIMARIO       68555    N           Comun

[1] "X"                  "CUE"                "Departamento"      
 [4] "Localidad"          "CP"                 "EsPrivada"         
 [7] "Turno"              "Curso"              "PeriodoEvaluatorio"
[10] "Documento"          "AnioLectivo"        "Asignatura"        
[13] "Nota"               "NivelEnsenanza"     "Division"          
[16] "EsMultianio"        "ModEnsenanza"

[1] 43476    17

[1] "X"                    "CUE"                  "Departamento"        
 [4] "Localidad"            "CP"                   "EsPrivada"           
 [7] "Turno"                "Curso"                "PeriodoEvaluatorio"  
[10] "Documento"            "AnioLectivo"          "Asignatura"          
[13] "NotasTercerTPrimario" "NivelEnsenanza"       "Division"            
[16] "EsMultianio"          "ModEnsenanza"

In [25]:
union1Primaria <- merge(x=PrimerTPrimario, y=SegundoTPrimario, by= c("Documento", "Asignatura"))
dim(union1Primaria)

[1] 54453    32

In [26]:
union2Primaria<-merge(x = union1Primaria, y=TercerTPrimario , by = c("Documento", "Asignatura"))
dim(union2Primaria)
head(union2Primaria,1)
names(union2Primaria)

[1] 92019    47

Documento Asignatura X.x  CUE.x   Departamento.x Localidad.x CP.x EsPrivada.x
1 48958572  MATEMATICA 2258 9005370 NOGOYA         NOGOYÁ      3158 N          
  Turno.x Curso.x ... EsPrivada Turno  Curso PeriodoEvaluatorio AnioLectivo
1 MAÑANA  6       ... N         MAÑANA 6     Tercer Trimestre   2023       
  NotasTercerTPrimario NivelEnsenanza Division EsMultianio ModEnsenanza
1 6                    PRIMARIO       66952    N           Comun

[1] "Documento"             "Asignatura"            "X.x"                  
 [4] "CUE.x"                 "Departamento.x"        "Localidad.x"          
 [7] "CP.x"                  "EsPrivada.x"           "Turno.x"              
[10] "Curso.x"               "PeriodoEvaluatorio.x"  "AnioLectivo.x"        
[13] "NotasPrimerTPrimario"  "NivelEnsenanza.x"      "Division.x"           
[16] "EsMultianio.x"         "ModEnsenanza.x"        "X.y"                  
[19] "CUE.y"                 "Departamento.y"        "Localidad.y"          
[22] "CP.y"                  "EsPrivada.y"           "Turno.y"              
[25] "Curso.y"               "PeriodoEvaluatorio.y"  "AnioLectivo.y"        
[28] "NotasSegundoTPrimario" "NivelEnsenanza.y"      "Division.y"           
[31] "EsMultianio.y"         "ModEnsenanza.y"        "X"                    
[34] "CUE"                   "Departamento"          "Localidad"            
[37] "CP"                    "EsPrivada"             "Turno"                
[40] "Curso"                 "PeriodoEvaluatorio"    "AnioLectivo"          
[43] "NotasTercerTPrimario"  "NivelEnsenanza"        "Division"             
[46] "EsMultianio"           "ModEnsenanza"

In [27]:
#Seleccionamos solo las columnas que nos interesan para nuestro analisis
Notas_NOGOYA_PRIMARIA<-select(union2Primaria, 'CUE', 'Departamento', 'Localidad', 'EsPrivada', 'Turno' , 'Curso' , 'PeriodoEvaluatorio' , 'Documento', 'Asignatura', 'NivelEnsenanza', 'ModEnsenanza', 'AnioLectivo','NotasPrimerTPrimario','NotasSegundoTPrimario', 'NotasTercerTPrimario')
dim(Notas_NOGOYA_PRIMARIA)
head(Notas_NOGOYA_PRIMARIA,10)

[1] 92019    15

CUE     Departamento Localidad EsPrivada Turno  Curso PeriodoEvaluatorio
1  9005370 NOGOYA       NOGOYÁ    N         MAÑANA 6     Tercer Trimestre  
2  9005370 NOGOYA       NOGOYÁ    N         MAÑANA 6     Tercer Trimestre  
3  9005370 NOGOYA       NOGOYÁ    N         MAÑANA 6     Tercer Trimestre  
4  9005370 NOGOYA       NOGOYÁ    N         MAÑANA 6     Tercer Trimestre  
5  9005370 NOGOYA       NOGOYÁ    N         MAÑANA 6     Tercer Trimestre  
6  9005370 NOGOYA       NOGOYÁ    N         MAÑANA 6     Tercer Trimestre  
7  9005370 NOGOYA       NOGOYÁ    N         MAÑANA 6     Tercer Trimestre  
8  9005370 NOGOYA       NOGOYÁ    N         MAÑANA 6     Tercer Trimestre  
9  9005370 NOGOYA       NOGOYÁ    N         MAÑANA 6     Tercer Trimestre  
10 9005370 NOGOYA       NOGOYÁ    N         MAÑANA 6     Tercer Trimestre  
   Documento Asignatura NivelEnsenanza ModEnsenanza AnioLectivo
1  48958572  MATEMATICA PRIMARIO       Comun        2023       
2  48958572  MATEMATICA PRIMARIO       Comun        2023       
3  48958572  MATEMATICA PRIMARIO       Comun        2023       
4  48958572  MATEMATICA PRIMARIO       Comun        2023       
5  48958572  MATEMATICA PRIMARIO       Comun        2023       
6  48958572  MATEMATICA PRIMARIO       Comun        2023       
7  48958572  MATEMATICA PRIMARIO       Comun        2023       
8  48958572  MATEMATICA PRIMARIO       Comun        2023       
9  48958572  MATEMATICA PRIMARIO       Comun        2023       
10 48958572  MATEMATICA PRIMARIO       Comun        2023       
   NotasPrimerTPrimario NotasSegundoTPrimario NotasTercerTPrimario
1  6                    6                     6                   
2  6                    6                     6                   
3  6                    6                     6                   
4  6                    6                     6                   
5  6                    6                     6                   
6  6                    6                     6                   
7  6                    6                     6                   
8  6                    6                     6                   
9  6                    6                     6                   
10 6                    6                     6

### Creamos la columna Promedio ###

In [28]:
Notas_NOGOYA_PRIMARIA$Promedio<-round((as.numeric(Notas_NOGOYA_PRIMARIA$NotasPrimerTPrimario)+as.numeric(Notas_NOGOYA_PRIMARIA$NotasSegundoTPrimario)+as.numeric(Notas_NOGOYA_PRIMARIA$NotasTercerTPrimario))/3,2)
head(Notas_NOGOYA_PRIMARIA,10)
dim(Notas_NOGOYA_PRIMARIA)

Warning message in eval(expr, envir, enclos):
"NAs introducidos por coerción"
Warning message in eval(expr, envir, enclos):
"NAs introducidos por coerción"
Warning message in eval(expr, envir, enclos):
"NAs introducidos por coerción"


CUE     Departamento Localidad EsPrivada Turno  Curso PeriodoEvaluatorio
1  9005370 NOGOYA       NOGOYÁ    N         MAÑANA 6     Tercer Trimestre  
2  9005370 NOGOYA       NOGOYÁ    N         MAÑANA 6     Tercer Trimestre  
3  9005370 NOGOYA       NOGOYÁ    N         MAÑANA 6     Tercer Trimestre  
4  9005370 NOGOYA       NOGOYÁ    N         MAÑANA 6     Tercer Trimestre  
5  9005370 NOGOYA       NOGOYÁ    N         MAÑANA 6     Tercer Trimestre  
6  9005370 NOGOYA       NOGOYÁ    N         MAÑANA 6     Tercer Trimestre  
7  9005370 NOGOYA       NOGOYÁ    N         MAÑANA 6     Tercer Trimestre  
8  9005370 NOGOYA       NOGOYÁ    N         MAÑANA 6     Tercer Trimestre  
9  9005370 NOGOYA       NOGOYÁ    N         MAÑANA 6     Tercer Trimestre  
10 9005370 NOGOYA       NOGOYÁ    N         MAÑANA 6     Tercer Trimestre  
   Documento Asignatura NivelEnsenanza ModEnsenanza AnioLectivo
1  48958572  MATEMATICA PRIMARIO       Comun        2023       
2  48958572  MATEMATICA PRIMARIO       Comun        2023       
3  48958572  MATEMATICA PRIMARIO       Comun        2023       
4  48958572  MATEMATICA PRIMARIO       Comun        2023       
5  48958572  MATEMATICA PRIMARIO       Comun        2023       
6  48958572  MATEMATICA PRIMARIO       Comun        2023       
7  48958572  MATEMATICA PRIMARIO       Comun        2023       
8  48958572  MATEMATICA PRIMARIO       Comun        2023       
9  48958572  MATEMATICA PRIMARIO       Comun        2023       
10 48958572  MATEMATICA PRIMARIO       Comun        2023       
   NotasPrimerTPrimario NotasSegundoTPrimario NotasTercerTPrimario Promedio
1  6                    6                     6                    6       
2  6                    6                     6                    6       
3  6                    6                     6                    6       
4  6                    6                     6                    6       
5  6                    6                     6                    6       
6  6                    6                     6                    6       
7  6                    6                     6                    6       
8  6                    6                     6                    6       
9  6                    6                     6                    6       
10 6                    6                     6                    6

[1] 92019    16

In [29]:
Notas_NOGOYA_PRIMARIA$NotasPrimerTPrimario[Notas_NOGOYA_PRIMARIA$NotasPrimerTPrimario == "NULL"] <- NA
Notas_NOGOYA_PRIMARIA$NotasSegundoTPrimario[Notas_NOGOYA_PRIMARIA$NotasSegundoTPrimario == "NULL"] <- NA
Notas_NOGOYA_PRIMARIA$NotasTercerTPrimario[Notas_NOGOYA_PRIMARIA$NotasTercerTPrimario == "NULL"] <- NA

In [30]:
# Verificar cuántos NAs hay en cada columna
colSums(is.na(Notas_NOGOYA_PRIMARIA))


CUE          Departamento             Localidad 
                    0                     0                     0 
            EsPrivada                 Turno                 Curso 
                    0                     0                     0 
   PeriodoEvaluatorio             Documento            Asignatura 
                    0                     0                     0 
       NivelEnsenanza          ModEnsenanza           AnioLectivo 
                    0                     0                     0 
 NotasPrimerTPrimario NotasSegundoTPrimario  NotasTercerTPrimario 
                 1022                   930                   897 
             Promedio 
                 4954

In [31]:
# Crear un nuevo dataset sin los NA en las columnas especificadas
Notas_NOGOYA_PRIMARIA_SIN_NA <- Notas_NOGOYA_PRIMARIA[complete.cases(Notas_NOGOYA_PRIMARIA[, c("NotasPrimerTPrimario", "NotasSegundoTPrimario", "NotasTercerTPrimario")]), ]


In [32]:
# Verificar cuántos NAs hay en cada columna
colSums(is.na(Notas_NOGOYA_PRIMARIA_SIN_NA))


CUE          Departamento             Localidad 
                    0                     0                     0 
            EsPrivada                 Turno                 Curso 
                    0                     0                     0 
   PeriodoEvaluatorio             Documento            Asignatura 
                    0                     0                     0 
       NivelEnsenanza          ModEnsenanza           AnioLectivo 
                    0                     0                     0 
 NotasPrimerTPrimario NotasSegundoTPrimario  NotasTercerTPrimario 
                    0                     0                     0 
             Promedio 
                 3898

In [33]:
#Notas_NOGOYA_PRIMARIA_SIN_NA <- filter(Notas_NOGOYA_PRIMARIA, !is.na(NotasPrimerTPrimario) | !is.na(NotasSegundoTPrimario) | !is.na(NotasTercerTPrimario))

In [34]:
dim(Notas_NOGOYA_PRIMARIA_SIN_NA)

[1] 90963    16

In [35]:
table(Notas_NOGOYA_PRIMARIA_SIN_NA$NotasPrimerTPrimario)


   10     6     7     8     9  EPAC 
 4489  7268 16940 33884 26907  1475 

In [36]:
table(Notas_NOGOYA_PRIMARIA_SIN_NA$NotasSegundoTPrimario)


   10     6     7     8     9  EPAC 
10730  6364 12820 28402 30240  2407 

In [37]:
table(Notas_NOGOYA_PRIMARIA_SIN_NA$NotasTercerTPrimario)


   10     6     7     8     9  EPAC 
21110  5819 10796 22348 28030  2860 

## LIMPIEZA EPAC ##

In [38]:
EPAC_tercerT <- filter(Notas_NOGOYA_PRIMARIA_SIN_NA, NotasTercerTPrimario == 'EPAC')
table(EPAC_tercerT$NotasTercerTPrimario)
head(EPAC_tercerT,30)


EPAC 
2860 

CUE     Departamento Localidad EsPrivada Turno    Curso PeriodoEvaluatorio
1  9005370 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
2  9005370 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
3  9005547 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
4  9005373 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
5  9005373 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
6  9003582 NOGOYA       NOGOYÁ    N         COMPLETO 6     Tercer Trimestre  
7  9003582 NOGOYA       NOGOYÁ    N         COMPLETO 6     Tercer Trimestre  
8  9003582 NOGOYA       NOGOYÁ    N         COMPLETO 6     Tercer Trimestre  
9  9003582 NOGOYA       NOGOYÁ    N         COMPLETO 6     Tercer Trimestre  
10 9003582 NOGOYA       NOGOYÁ    N         COMPLETO 6     Tercer Trimestre  
11 9003582 NOGOYA       NOGOYÁ    N         COMPLETO 6     Tercer Trimestre  
12 9003582 NOGOYA       NOGOYÁ    N         COMPLETO 6     Tercer Trimestre  
13 9003582 NOGOYA       NOGOYÁ    N         COMPLETO 6     Tercer Trimestre  
14 9003582 NOGOYA       NOGOYÁ    N         COMPLETO 6     Tercer Trimestre  
15 9003582 NOGOYA       NOGOYÁ    N         COMPLETO 6     Tercer Trimestre  
16 9003582 NOGOYA       NOGOYÁ    N         COMPLETO 6     Tercer Trimestre  
17 9003582 NOGOYA       NOGOYÁ    N         COMPLETO 6     Tercer Trimestre  
18 9003582 NOGOYA       NOGOYÁ    N         COMPLETO 6     Tercer Trimestre  
19 9003582 NOGOYA       NOGOYÁ    N         COMPLETO 6     Tercer Trimestre  
20 9003582 NOGOYA       NOGOYÁ    N         COMPLETO 6     Tercer Trimestre  
21 9003582 NOGOYA       NOGOYÁ    N         COMPLETO 6     Tercer Trimestre  
22 9005370 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
23 9005370 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
24 9005373 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
25 9005367 NOGOYA       NOGOYÁ    S         MAÑANA   6     Tercer Trimestre  
26 9005367 NOGOYA       NOGOYÁ    S         MAÑANA   6     Tercer Trimestre  
27 9005367 NOGOYA       NOGOYÁ    S         MAÑANA   6     Tercer Trimestre  
28 9005367 NOGOYA       NOGOYÁ    S         MAÑANA   6     Tercer Trimestre  
29 9005367 NOGOYA       NOGOYÁ    S         MAÑANA   6     Tercer Trimestre  
30 9005367 NOGOYA       NOGOYÁ    S         MAÑANA   6     Tercer Trimestre  
   Documento Asignatura        NivelEnsenanza ModEnsenanza AnioLectivo
1  49224307  MATEMATICA        PRIMARIO       Comun        2023       
2  49224307  MATEMATICA        PRIMARIO       Comun        2023       
3  49438965  LENGUA            PRIMARIO       Comun        2023       
4  49565265  LENGUA            PRIMARIO       Comun        2023       
5  49565265  MATEMATICA        PRIMARIO       Comun        2023       
6  49817076  LENGUA            PRIMARIO       Comun        2023       
7  49817076  LENGUA            PRIMARIO       Comun        2023       
8  49817076  LENGUA            PRIMARIO       Comun        2023       
9  49817076  LENGUA            PRIMARIO       Comun        2023       
10 49817076  LENGUA            PRIMARIO       Comun        2023       
11 49817076  LENGUA            PRIMARIO       Comun        2023       
12 49817076  LENGUA            PRIMARIO       Comun        2023       
13 49817076  LENGUA            PRIMARIO       Comun        2023       
14 49817076  MATEMATICA        PRIMARIO       Comun        2023       
15 49817076  MATEMATICA        PRIMARIO       Comun        2023       
16 49817076  MATEMATICA        PRIMARIO       Comun        2023       
17 49817076  MATEMATICA        PRIMARIO       Comun        2023       
18 49817076  MATEMATICA        PRIMARIO       Comun        2023       
19 49817076  MATEMATICA        PRIMARIO       Comun        2023       
20 49817076  MATEMATICA        PRIMARIO       Comun        2023       
21 49817076  MATEMATICA        PRIMARIO       Comun        2023       
22 50247480  MATEMATICA

In [39]:
#El promedio para los que tengan EPAC en el tercer trimestre sera Desaprobado
EPAC_tercerT$Promedio <- "Desaprobado"

In [40]:
head(EPAC_tercerT,30)

CUE     Departamento Localidad EsPrivada Turno    Curso PeriodoEvaluatorio
1  9005370 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
2  9005370 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
3  9005547 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
4  9005373 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
5  9005373 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
6  9003582 NOGOYA       NOGOYÁ    N         COMPLETO 6     Tercer Trimestre  
7  9003582 NOGOYA       NOGOYÁ    N         COMPLETO 6     Tercer Trimestre  
8  9003582 NOGOYA       NOGOYÁ    N         COMPLETO 6     Tercer Trimestre  
9  9003582 NOGOYA       NOGOYÁ    N         COMPLETO 6     Tercer Trimestre  
10 9003582 NOGOYA       NOGOYÁ    N         COMPLETO 6     Tercer Trimestre  
11 9003582 NOGOYA       NOGOYÁ    N         COMPLETO 6     Tercer Trimestre  
12 9003582 NOGOYA       NOGOYÁ    N         COMPLETO 6     Tercer Trimestre  
13 9003582 NOGOYA       NOGOYÁ    N         COMPLETO 6     Tercer Trimestre  
14 9003582 NOGOYA       NOGOYÁ    N         COMPLETO 6     Tercer Trimestre  
15 9003582 NOGOYA       NOGOYÁ    N         COMPLETO 6     Tercer Trimestre  
16 9003582 NOGOYA       NOGOYÁ    N         COMPLETO 6     Tercer Trimestre  
17 9003582 NOGOYA       NOGOYÁ    N         COMPLETO 6     Tercer Trimestre  
18 9003582 NOGOYA       NOGOYÁ    N         COMPLETO 6     Tercer Trimestre  
19 9003582 NOGOYA       NOGOYÁ    N         COMPLETO 6     Tercer Trimestre  
20 9003582 NOGOYA       NOGOYÁ    N         COMPLETO 6     Tercer Trimestre  
21 9003582 NOGOYA       NOGOYÁ    N         COMPLETO 6     Tercer Trimestre  
22 9005370 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
23 9005370 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
24 9005373 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
25 9005367 NOGOYA       NOGOYÁ    S         MAÑANA   6     Tercer Trimestre  
26 9005367 NOGOYA       NOGOYÁ    S         MAÑANA   6     Tercer Trimestre  
27 9005367 NOGOYA       NOGOYÁ    S         MAÑANA   6     Tercer Trimestre  
28 9005367 NOGOYA       NOGOYÁ    S         MAÑANA   6     Tercer Trimestre  
29 9005367 NOGOYA       NOGOYÁ    S         MAÑANA   6     Tercer Trimestre  
30 9005367 NOGOYA       NOGOYÁ    S         MAÑANA   6     Tercer Trimestre  
   Documento Asignatura        NivelEnsenanza ModEnsenanza AnioLectivo
1  49224307  MATEMATICA        PRIMARIO       Comun        2023       
2  49224307  MATEMATICA        PRIMARIO       Comun        2023       
3  49438965  LENGUA            PRIMARIO       Comun        2023       
4  49565265  LENGUA            PRIMARIO       Comun        2023       
5  49565265  MATEMATICA        PRIMARIO       Comun        2023       
6  49817076  LENGUA            PRIMARIO       Comun        2023       
7  49817076  LENGUA            PRIMARIO       Comun        2023       
8  49817076  LENGUA            PRIMARIO       Comun        2023       
9  49817076  LENGUA            PRIMARIO       Comun        2023       
10 49817076  LENGUA            PRIMARIO       Comun        2023       
11 49817076  LENGUA            PRIMARIO       Comun        2023       
12 49817076  LENGUA            PRIMARIO       Comun        2023       
13 49817076  LENGUA            PRIMARIO       Comun        2023       
14 49817076  MATEMATICA        PRIMARIO       Comun        2023       
15 49817076  MATEMATICA        PRIMARIO       Comun        2023       
16 49817076  MATEMATICA        PRIMARIO       Comun        2023       
17 49817076  MATEMATICA        PRIMARIO       Comun        2023       
18 49817076  MATEMATICA        PRIMARIO       Comun        2023       
19 49817076  MATEMATICA        PRIMARIO       Comun        2023       
20 49817076  MATEMATICA        PRIMARIO       Comun        2023       
21 49817076  MATEMATICA        PRIMARIO       Comun        2023       
22 50247480  MATEMATICA

In [41]:
#Filtro para pbtener quienes tienen EPAC en el primer y/o segundo trimestre pero no en el tercero
EPAC_Primer_SegundoT <- filter(Notas_NOGOYA_PRIMARIA_SIN_NA, NotasPrimerTPrimario == 'EPAC' & NotasTercerTPrimario != 'EPAC' | NotasSegundoTPrimario == 'EPAC' & NotasTercerTPrimario != 'EPAC')
table(EPAC_Primer_SegundoT$NotasTercerTPrimario)
head(EPAC_Primer_SegundoT,30)


  6   7   8   9 
520 338 178   2 

CUE     Departamento Localidad EsPrivada Turno    Curso PeriodoEvaluatorio
1  9000303 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
2  9000303 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
3  9000303 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
4  9000303 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
5  9000303 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
6  9000303 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
7  9000303 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
8  9000303 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
9  9000303 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
10 9000303 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
11 9000303 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
12 9000303 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
13 9000303 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
14 9000303 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
15 9000303 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
16 9000303 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
17 9000303 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
18 9000303 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
19 9000303 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
20 9000303 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
21 9000303 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
22 9000303 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
23 9000303 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
24 9000303 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
25 9000303 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
26 9000303 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
27 9000303 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
28 9005541 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
29 9005541 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
30 9003582 NOGOYA       NOGOYÁ    N         COMPLETO 6     Tercer Trimestre  
   Documento Asignatura              NivelEnsenanza ModEnsenanza AnioLectivo
1  49439813  EDUCACION FISICA        PRIMARIO       Comun        2023       
2  49439813  EDUCACION FISICA        PRIMARIO       Comun        2023       
3  49439813  EDUCACION FISICA        PRIMARIO       Comun        2023       
4  49439813  EDUCACION FISICA        PRIMARIO       Comun        2023       
5  49439813  EDUCACION FISICA        PRIMARIO       Comun        2023       
6  49439813  EDUCACION FISICA        PRIMARIO       Comun        2023       
7  49439813  EDUCACION FISICA        PRIMARIO       Comun        2023       
8  49439813  EDUCACION FISICA        PRIMARIO       Comun        2023       
9  49439813  EDUCACION FISICA        PRIMARIO       Comun        2023       
10 49439813  EDUCACION FISICA        PRIMARIO       Comun        2023       
11 49439813  EDUCACION FISICA        PRIMARIO       Comun        2023       
12 49439813  EDUCACION FISICA        PRIMARIO       Comun        2023       
13 49439813  EDUCACION FISICA        PRIMARIO       Comun        2023       
14 49439813  EDUCACION FISICA        PRIMARIO       Comun        2023       
15 49439813  EDUCACION FISICA        PRIMARIO       Comun        2023       
16 49439813  EDUCACION FISICA        PRIMARIO       Comun        2023       
17 49439813  EDUCACION FISICA        PRIMARIO       Comun        2023       
18 49439813  EDUCACION FISICA        PRIMARIO       Comun        2023       
19 49439813  EDUCACION FISICA        PRIMARIO       Comun        2023       
20 49439813  EDUCACION FISICA        PRIMARIO

In [42]:
#El promedio de los que tienen EPAC en algun trimestre pero no en el tercero sera la nota del tercer trimestre
EPAC_Primer_SegundoT$Promedio <- EPAC_Primer_SegundoT$NotasTercerTPrimario

In [43]:
head(EPAC_Primer_SegundoT,30)

CUE     Departamento Localidad EsPrivada Turno    Curso PeriodoEvaluatorio
1  9000303 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
2  9000303 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
3  9000303 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
4  9000303 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
5  9000303 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
6  9000303 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
7  9000303 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
8  9000303 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
9  9000303 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
10 9000303 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
11 9000303 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
12 9000303 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
13 9000303 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
14 9000303 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
15 9000303 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
16 9000303 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
17 9000303 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
18 9000303 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
19 9000303 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
20 9000303 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
21 9000303 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
22 9000303 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
23 9000303 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
24 9000303 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
25 9000303 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
26 9000303 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
27 9000303 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
28 9005541 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
29 9005541 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
30 9003582 NOGOYA       NOGOYÁ    N         COMPLETO 6     Tercer Trimestre  
   Documento Asignatura              NivelEnsenanza ModEnsenanza AnioLectivo
1  49439813  EDUCACION FISICA        PRIMARIO       Comun        2023       
2  49439813  EDUCACION FISICA        PRIMARIO       Comun        2023       
3  49439813  EDUCACION FISICA        PRIMARIO       Comun        2023       
4  49439813  EDUCACION FISICA        PRIMARIO       Comun        2023       
5  49439813  EDUCACION FISICA        PRIMARIO       Comun        2023       
6  49439813  EDUCACION FISICA        PRIMARIO       Comun        2023       
7  49439813  EDUCACION FISICA        PRIMARIO       Comun        2023       
8  49439813  EDUCACION FISICA        PRIMARIO       Comun        2023       
9  49439813  EDUCACION FISICA        PRIMARIO       Comun        2023       
10 49439813  EDUCACION FISICA        PRIMARIO       Comun        2023       
11 49439813  EDUCACION FISICA        PRIMARIO       Comun        2023       
12 49439813  EDUCACION FISICA        PRIMARIO       Comun        2023       
13 49439813  EDUCACION FISICA        PRIMARIO       Comun        2023       
14 49439813  EDUCACION FISICA        PRIMARIO       Comun        2023       
15 49439813  EDUCACION FISICA        PRIMARIO       Comun        2023       
16 49439813  EDUCACION FISICA        PRIMARIO       Comun        2023       
17 49439813  EDUCACION FISICA        PRIMARIO       Comun        2023       
18 49439813  EDUCACION FISICA        PRIMARIO       Comun        2023       
19 49439813  EDUCACION FISICA        PRIMARIO       Comun        2023       
20 49439813  EDUCACION FISICA        PRIMARIO

In [44]:
#Extraigo por separado los que no tienen EPAC para luego unirlo con los otros dos datasets con EPAC
Sin_EPAC <- filter(Notas_NOGOYA_PRIMARIA_SIN_NA, NotasPrimerTPrimario != 'EPAC'& NotasSegundoTPrimario != 'EPAC' & NotasTercerTPrimario != 'EPAC')
table(Sin_EPAC$NotasPrimerTPrimario)
table(Sin_EPAC$NotasSegundoTPrimario)
table(Sin_EPAC$NotasTercerTPrimario)
head(Sin_EPAC,30)


   10     6     7     8     9 
 4489  5461 16548 33667 26900 


   10     6     7     8     9 
10730  5268 12481 28352 30234 


   10     6     7     8     9 
21110  5299 10458 22170 28028 

CUE     Departamento Localidad EsPrivada Turno  Curso PeriodoEvaluatorio
1  9005370 NOGOYA       NOGOYÁ    N         MAÑANA 6     Tercer Trimestre  
2  9005370 NOGOYA       NOGOYÁ    N         MAÑANA 6     Tercer Trimestre  
3  9005370 NOGOYA       NOGOYÁ    N         MAÑANA 6     Tercer Trimestre  
4  9005370 NOGOYA       NOGOYÁ    N         MAÑANA 6     Tercer Trimestre  
5  9005370 NOGOYA       NOGOYÁ    N         MAÑANA 6     Tercer Trimestre  
6  9005370 NOGOYA       NOGOYÁ    N         MAÑANA 6     Tercer Trimestre  
7  9005370 NOGOYA       NOGOYÁ    N         MAÑANA 6     Tercer Trimestre  
8  9005370 NOGOYA       NOGOYÁ    N         MAÑANA 6     Tercer Trimestre  
9  9005370 NOGOYA       NOGOYÁ    N         MAÑANA 6     Tercer Trimestre  
10 9005370 NOGOYA       NOGOYÁ    N         MAÑANA 6     Tercer Trimestre  
11 9005370 NOGOYA       NOGOYÁ    N         MAÑANA 6     Tercer Trimestre  
12 9005370 NOGOYA       NOGOYÁ    N         MAÑANA 6     Tercer Trimestre  
13 9005370 NOGOYA       NOGOYÁ    N         MAÑANA 6     Tercer Trimestre  
14 9005370 NOGOYA       NOGOYÁ    N         MAÑANA 6     Tercer Trimestre  
15 9005370 NOGOYA       NOGOYÁ    N         MAÑANA 6     Tercer Trimestre  
16 9005370 NOGOYA       NOGOYÁ    N         MAÑANA 6     Tercer Trimestre  
17 9005547 NOGOYA       NOGOYÁ    N         MAÑANA 6     Tercer Trimestre  
18 9005547 NOGOYA       NOGOYÁ    N         MAÑANA 6     Tercer Trimestre  
19 9005547 NOGOYA       NOGOYÁ    N         MAÑANA 6     Tercer Trimestre  
20 9005547 NOGOYA       NOGOYÁ    N         MAÑANA 6     Tercer Trimestre  
21 9005547 NOGOYA       NOGOYÁ    N         MAÑANA 6     Tercer Trimestre  
22 9005547 NOGOYA       NOGOYÁ    N         MAÑANA 6     Tercer Trimestre  
23 9005547 NOGOYA       NOGOYÁ    N         MAÑANA 6     Tercer Trimestre  
24 9005547 NOGOYA       NOGOYÁ    N         MAÑANA 6     Tercer Trimestre  
25 9005547 NOGOYA       NOGOYÁ    N         MAÑANA 6     Tercer Trimestre  
26 9005547 NOGOYA       NOGOYÁ    N         MAÑANA 6     Tercer Trimestre  
27 9005547 NOGOYA       NOGOYÁ    N         MAÑANA 6     Tercer Trimestre  
28 9005547 NOGOYA       NOGOYÁ    N         MAÑANA 6     Tercer Trimestre  
29 9005547 NOGOYA       NOGOYÁ    N         MAÑANA 6     Tercer Trimestre  
30 9000303 NOGOYA       NOGOYÁ    N         MAÑANA 6     Tercer Trimestre  
   Documento Asignatura                          NivelEnsenanza ModEnsenanza
1  48958572  MATEMATICA                          PRIMARIO       Comun       
2  48958572  MATEMATICA                          PRIMARIO       Comun       
3  48958572  MATEMATICA                          PRIMARIO       Comun       
4  48958572  MATEMATICA                          PRIMARIO       Comun       
5  48958572  MATEMATICA                          PRIMARIO       Comun       
6  48958572  MATEMATICA                          PRIMARIO       Comun       
7  48958572  MATEMATICA                          PRIMARIO       Comun       
8  48958572  MATEMATICA                          PRIMARIO       Comun       
9  48958572  MATEMATICA                          PRIMARIO       Comun       
10 48958572  MATEMATICA                          PRIMARIO       Comun       
11 48958572  MATEMATICA                          PRIMARIO       Comun       
12 48958572  MATEMATICA                          PRIMARIO       Comun       
13 48958572  MATEMATICA                          PRIMARIO       Comun       
14 48958572  MATEMATICA                          PRIMARIO       Comun       
15 48958572  MATEMATICA                          PRIMARIO       Comun       
16 48958572  MATEMATICA                          PRIMARIO       Comun       
17 49438965  ACOMPAÑAMIENTO AL ESTUDIO           PRIMARIO       Comun       
18 49438965  ARTES VISUALES                      PRIMARIO       Comun       
19 49438965  CIENCIAS NATURALES                  PRIMARIO       Comun       
20 49438965  CIENCIAS SOCIALES                   PRIMARIO       Comun       
21 49438965  EDUC. FISICA EN E

In [45]:
Primaria_filtrado <- rbind(EPAC_tercerT, EPAC_Primer_SegundoT, Sin_EPAC )

In [46]:
head(Primaria_filtrado,30)

CUE     Departamento Localidad EsPrivada Turno    Curso PeriodoEvaluatorio
1  9005370 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
2  9005370 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
3  9005547 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
4  9005373 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
5  9005373 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
6  9003582 NOGOYA       NOGOYÁ    N         COMPLETO 6     Tercer Trimestre  
7  9003582 NOGOYA       NOGOYÁ    N         COMPLETO 6     Tercer Trimestre  
8  9003582 NOGOYA       NOGOYÁ    N         COMPLETO 6     Tercer Trimestre  
9  9003582 NOGOYA       NOGOYÁ    N         COMPLETO 6     Tercer Trimestre  
10 9003582 NOGOYA       NOGOYÁ    N         COMPLETO 6     Tercer Trimestre  
11 9003582 NOGOYA       NOGOYÁ    N         COMPLETO 6     Tercer Trimestre  
12 9003582 NOGOYA       NOGOYÁ    N         COMPLETO 6     Tercer Trimestre  
13 9003582 NOGOYA       NOGOYÁ    N         COMPLETO 6     Tercer Trimestre  
14 9003582 NOGOYA       NOGOYÁ    N         COMPLETO 6     Tercer Trimestre  
15 9003582 NOGOYA       NOGOYÁ    N         COMPLETO 6     Tercer Trimestre  
16 9003582 NOGOYA       NOGOYÁ    N         COMPLETO 6     Tercer Trimestre  
17 9003582 NOGOYA       NOGOYÁ    N         COMPLETO 6     Tercer Trimestre  
18 9003582 NOGOYA       NOGOYÁ    N         COMPLETO 6     Tercer Trimestre  
19 9003582 NOGOYA       NOGOYÁ    N         COMPLETO 6     Tercer Trimestre  
20 9003582 NOGOYA       NOGOYÁ    N         COMPLETO 6     Tercer Trimestre  
21 9003582 NOGOYA       NOGOYÁ    N         COMPLETO 6     Tercer Trimestre  
22 9005370 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
23 9005370 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
24 9005373 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
25 9005367 NOGOYA       NOGOYÁ    S         MAÑANA   6     Tercer Trimestre  
26 9005367 NOGOYA       NOGOYÁ    S         MAÑANA   6     Tercer Trimestre  
27 9005367 NOGOYA       NOGOYÁ    S         MAÑANA   6     Tercer Trimestre  
28 9005367 NOGOYA       NOGOYÁ    S         MAÑANA   6     Tercer Trimestre  
29 9005367 NOGOYA       NOGOYÁ    S         MAÑANA   6     Tercer Trimestre  
30 9005367 NOGOYA       NOGOYÁ    S         MAÑANA   6     Tercer Trimestre  
   Documento Asignatura        NivelEnsenanza ModEnsenanza AnioLectivo
1  49224307  MATEMATICA        PRIMARIO       Comun        2023       
2  49224307  MATEMATICA        PRIMARIO       Comun        2023       
3  49438965  LENGUA            PRIMARIO       Comun        2023       
4  49565265  LENGUA            PRIMARIO       Comun        2023       
5  49565265  MATEMATICA        PRIMARIO       Comun        2023       
6  49817076  LENGUA            PRIMARIO       Comun        2023       
7  49817076  LENGUA            PRIMARIO       Comun        2023       
8  49817076  LENGUA            PRIMARIO       Comun        2023       
9  49817076  LENGUA            PRIMARIO       Comun        2023       
10 49817076  LENGUA            PRIMARIO       Comun        2023       
11 49817076  LENGUA            PRIMARIO       Comun        2023       
12 49817076  LENGUA            PRIMARIO       Comun        2023       
13 49817076  LENGUA            PRIMARIO       Comun        2023       
14 49817076  MATEMATICA        PRIMARIO       Comun        2023       
15 49817076  MATEMATICA        PRIMARIO       Comun        2023       
16 49817076  MATEMATICA        PRIMARIO       Comun        2023       
17 49817076  MATEMATICA        PRIMARIO       Comun        2023       
18 49817076  MATEMATICA        PRIMARIO       Comun        2023       
19 49817076  MATEMATICA        PRIMARIO       Comun        2023       
20 49817076  MATEMATICA        PRIMARIO       Comun        2023       
21 49817076  MATEMATICA        PRIMARIO       Comun        2023       
22 50247480  MATEMATICA

In [47]:
names(Primaria_filtrado)

[1] "CUE"                   "Departamento"          "Localidad"            
 [4] "EsPrivada"             "Turno"                 "Curso"                
 [7] "PeriodoEvaluatorio"    "Documento"             "Asignatura"           
[10] "NivelEnsenanza"        "ModEnsenanza"          "AnioLectivo"          
[13] "NotasPrimerTPrimario"  "NotasSegundoTPrimario" "NotasTercerTPrimario" 
[16] "Promedio"

### Columna Condicion ###

In [48]:
# Crear una nueva columna llamada condicion basada en la columna promedio
Primaria_filtrado <- Primaria_filtrado %>%
  mutate(Condicion = ifelse(Promedio == "Desaprobado", "DESAPROBADO", "APROBADO"))

# Verificar los primeros registros del dataframe resultante
head(Primaria_filtrado)
tail(Primaria_filtrado)

CUE     Departamento Localidad EsPrivada Turno    Curso PeriodoEvaluatorio
1 9005370 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
2 9005370 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
3 9005547 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
4 9005373 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
5 9005373 NOGOYA       NOGOYÁ    N         MAÑANA   6     Tercer Trimestre  
6 9003582 NOGOYA       NOGOYÁ    N         COMPLETO 6     Tercer Trimestre  
  Documento Asignatura NivelEnsenanza ModEnsenanza AnioLectivo
1 49224307  MATEMATICA PRIMARIO       Comun        2023       
2 49224307  MATEMATICA PRIMARIO       Comun        2023       
3 49438965  LENGUA     PRIMARIO       Comun        2023       
4 49565265  LENGUA     PRIMARIO       Comun        2023       
5 49565265  MATEMATICA PRIMARIO       Comun        2023       
6 49817076  LENGUA     PRIMARIO       Comun        2023       
  NotasPrimerTPrimario NotasSegundoTPrimario NotasTercerTPrimario Promedio   
1 6                    6                     EPAC                 Desaprobado
2 6                    6                     EPAC                 Desaprobado
3 6                    EPAC                  EPAC                 Desaprobado
4 7                    6                     EPAC                 Desaprobado
5 7                    6                     EPAC                 Desaprobado
6 EPAC                 EPAC                  EPAC                 Desaprobado
  Condicion  
1 DESAPROBADO
2 DESAPROBADO
3 DESAPROBADO
4 DESAPROBADO
5 DESAPROBADO
6 DESAPROBADO

CUE     Departamento Localidad EsPrivada Turno Curso PeriodoEvaluatorio
90958 9000300 NOGOYA       NOGOYÁ    S         TARDE 1     Tercer Trimestre  
90959 9000300 NOGOYA       NOGOYÁ    S         TARDE 1     Tercer Trimestre  
90960 9000300 NOGOYA       NOGOYÁ    S         TARDE 1     Tercer Trimestre  
90961 9000300 NOGOYA       NOGOYÁ    S         TARDE 1     Tercer Trimestre  
90962 9000300 NOGOYA       NOGOYÁ    S         TARDE 1     Tercer Trimestre  
90963 9000300 NOGOYA       NOGOYÁ    S         TARDE 1     Tercer Trimestre  
      Documento Asignatura            NivelEnsenanza ModEnsenanza AnioLectivo
90958 96127481  EDUCACION MUSICAL     PRIMARIO       Comun        2023       
90959 96127481  EDUCACION TECNOLOGICA PRIMARIO       Comun        2023       
90960 96127481  LENGUA                PRIMARIO       Comun        2023       
90961 96127481  MATEMATICA            PRIMARIO       Comun        2023       
90962 96127481  TALLER DE COMPUTACIÓN PRIMARIO       Comun        2023       
90963 96127481  TALLER DE INGLÉS      PRIMARIO       Comun        2023       
      NotasPrimerTPrimario NotasSegundoTPrimario NotasTercerTPrimario Promedio
90958 9                    10                    10                   9.67    
90959 9                    9                     9                    9       
90960 8                    9                     9                    8.67    
90961 8                    9                     9                    8.67    
90962 8                    8                     9                    8.33    
90963 8                    8                     8                    8       
      Condicion
90958 APROBADO 
90959 APROBADO 
90960 APROBADO 
90961 APROBADO 
90962 APROBADO 
90963 APROBADO

### Cantidad de alumnos ###

In [49]:
#vista general de los valores de la columna Asignatura
table(Primaria_filtrado$Asignatura)


            ACOM. AL ESTUDIO MATEMATICA- NATURALES 
                                                14 
                 ACOMP AL EST LENGUA Y CS SOCIALES 
                                               126 
           ACOMP AL EST MATEMÁTICA Y CS. NATURALES 
                                               126 
                 ACOMP. AL ESTUDIO LENGUA-SOCIALES 
                                                14 
                        ACOMP. EST LENG Y SOCIALES 
                                                43 
                              ACOMP. EST MAT Y NAT 
                                                43 
           ACOMPAÑAMIENTO AL EST. LENGUA Y C. SOC. 
                                                53 
                         ACOMPAÑAMIENTO AL ESTUDIO 
                                               119 
         ACOMPAÑAMIENTO AL ESTUDIO  C. NAT. Y MAT. 
                                                53 
ACOMPAÑAMIENTO AL ESTUDIO  MATEMATICA Y  NATURALES 
           

In [50]:
table(Primaria_filtrado$Curso)


    1     2     3     4     5     6 
12003 13071 13282 14993 18883 18731 

In [51]:
library('stringr')
Primaria_filtrado$Curso <- str_replace (Primaria_filtrado$Curso, "1" , "PRIMERO")
Primaria_filtrado$Curso <- str_replace (Primaria_filtrado$Curso, "2" , "SEGUNDO")
Primaria_filtrado$Curso <- str_replace (Primaria_filtrado$Curso, "3" , "TERCERO")
Primaria_filtrado$Curso <- str_replace (Primaria_filtrado$Curso, "4" , "CUARTO")
Primaria_filtrado$Curso <- str_replace (Primaria_filtrado$Curso, "5" , "QUINTO")
Primaria_filtrado$Curso <- str_replace (Primaria_filtrado$Curso, "6" , "SEXTO")


In [52]:
table (Primaria_filtrado$Curso)


 CUARTO PRIMERO  QUINTO SEGUNDO   SEXTO TERCERO 
  14993   12003   18883   13071   18731   13282 

In [53]:
lengua<-Primaria_filtrado %>% group_by(CUE,Asignatura) %>%  filter(Asignatura=="LENGUA") 
lengua

CUE     Departamento Localidad EsPrivada Turno    Curso  
1     9005547 NOGOYA       NOGOYÁ    N         MAÑANA   SEXTO  
2     9005373 NOGOYA       NOGOYÁ    N         MAÑANA   SEXTO  
3     9003582 NOGOYA       NOGOYÁ    N         COMPLETO SEXTO  
4     9003582 NOGOYA       NOGOYÁ    N         COMPLETO SEXTO  
5     9003582 NOGOYA       NOGOYÁ    N         COMPLETO SEXTO  
6     9003582 NOGOYA       NOGOYÁ    N         COMPLETO SEXTO  
7     9003582 NOGOYA       NOGOYÁ    N         COMPLETO SEXTO  
8     9003582 NOGOYA       NOGOYÁ    N         COMPLETO SEXTO  
9     9003582 NOGOYA       NOGOYÁ    N         COMPLETO SEXTO  
10    9003582 NOGOYA       NOGOYÁ    N         COMPLETO SEXTO  
11    9000309 NOGOYA       NOGOYÁ    N         MAÑANA   SEXTO  
12    9003450 NOGOYA       NOGOYÁ    N         MAÑANA   SEXTO  
13    9000309 NOGOYA       NOGOYÁ    N         MAÑANA   SEXTO  
14    9000303 NOGOYA       NOGOYÁ    N         MAÑANA   QUINTO 
15    9010173 NOGOYA       NOGOYÁ    S         TARDE    QUINTO 
16    9000303 NOGOYA       NOGOYÁ    N         MAÑANA   SEXTO  
17    9000309 NOGOYA       NOGOYÁ    N         MAÑANA   QUINTO 
18    9000303 NOGOYA       NOGOYÁ    N         MAÑANA   SEXTO  
19    9000309 NOGOYA       NOGOYÁ    N         TARDE    QUINTO 
20    9005349 NOGOYA       NOGOYÁ    N         TARDE    SEXTO  
21    9000309 NOGOYA       NOGOYÁ    N         MAÑANA   SEXTO  
22    9003450 NOGOYA       NOGOYÁ    N         MAÑANA   QUINTO 
23    9003450 NOGOYA       NOGOYÁ    N         MAÑANA   SEXTO  
24    9000309 NOGOYA       NOGOYÁ    N         MAÑANA   SEXTO  
25    9000303 NOGOYA       NOGOYÁ    N         TARDE    SEGUNDO
26    9005541 NOGOYA       NOGOYÁ    N         MAÑANA   QUINTO 
27    9005349 NOGOYA       NOGOYÁ    N         TARDE    SEXTO  
28    9005349 NOGOYA       NOGOYÁ    N         TARDE    SEXTO  
29    9005349 NOGOYA       NOGOYÁ    N         TARDE    SEXTO  
30    9005349 NOGOYA       NOGOYÁ    N         TARDE    SEXTO  
...   ...     ...          ...       ...       ...      ...    
11280 9027069 NOGOYA       NOGOYÁ    S         TARDE    PRIMERO
11281 9027069 NOGOYA       NOGOYÁ    S         TARDE    PRIMERO
11282 9027069 NOGOYA       NOGOYÁ    S         TARDE    PRIMERO
11283 9027069 NOGOYA       NOGOYÁ    S         TARDE    PRIMERO
11284 9027069 NOGOYA       NOGOYÁ    S         TARDE    PRIMERO
11285 9027069 NOGOYA       NOGOYÁ    S         TARDE    PRIMERO
11286 9027069 NOGOYA       NOGOYÁ    S         TARDE    PRIMERO
11287 9027069 NOGOYA       NOGOYÁ    S         TARDE    PRIMERO
11288 9027069 NOGOYA       NOGOYÁ    S         TARDE    PRIMERO
11289 9027069 NOGOYA       NOGOYÁ    S         TARDE    PRIMERO
11290 9027069 NOGOYA       NOGOYÁ    S         TARDE    PRIMERO
11291 9027069 NOGOYA       NOGOYÁ    S         TARDE    PRIMERO
11292 9005370 NOGOYA       NOGOYÁ    N         TARDE    PRIMERO
11293 9000309 NOGOYA       NOGOYÁ    N         MAÑANA   QUINTO 
11294 9003444 NOGOYA       NOGOYÁ    N         TARDE    TERCERO
11295 9000297 NOGOYA       NOGOYÁ    N         TARDE    QUINTO 
11296 9005541 NOGOYA       NOGOYÁ    N         TARDE    TERCERO
11297 9027069 NOGOYA       NOGOYÁ    S         TARDE    SEXTO  
11298 9027069 NOGOYA       NOGOYÁ    S         TARDE    PRIMERO
11299 9000300 NOGOYA       NOGOYÁ    S         TARDE    QUINTO 
11300 9000300 NOGOYA       NOGOYÁ    S         TARDE    QUINTO 
11301 9000300 NOGOYA       NOGOYÁ    S         TARDE    QUINTO 
11302 9000300 NOGOYA       NOGOYÁ    S         TARDE    QUINTO 
11303 9000300 NOGOYA       NOGOYÁ    S         TARDE    QUINTO 
11304 9000300 NOGOYA       NOGOYÁ    S         TARDE    QUINTO 
11305 9000300 NOGOYA       NOGOYÁ    S         TARDE    QUINTO 
11306 9000300 NOGOYA       NOGOYÁ    S         TARDE    QUINTO 
11307 9027069 NOGOYA       NOGOYÁ    S         TARDE    QUINTO 
11308 9005373 NOGOYA       NOGOYÁ    N         TARDE    TERCERO
11309 9000300 NOGOYA       NOGOYÁ    S         TARDE    PRIMERO
      PeriodoEvaluatorio Documento Asi

In [54]:
head(lengua,30)

CUE     Departamento Localidad EsPrivada Turno    Curso   PeriodoEvaluatorio
1  9005547 NOGOYA       NOGOYÁ    N         MAÑANA   SEXTO   Tercer Trimestre  
2  9005373 NOGOYA       NOGOYÁ    N         MAÑANA   SEXTO   Tercer Trimestre  
3  9003582 NOGOYA       NOGOYÁ    N         COMPLETO SEXTO   Tercer Trimestre  
4  9003582 NOGOYA       NOGOYÁ    N         COMPLETO SEXTO   Tercer Trimestre  
5  9003582 NOGOYA       NOGOYÁ    N         COMPLETO SEXTO   Tercer Trimestre  
6  9003582 NOGOYA       NOGOYÁ    N         COMPLETO SEXTO   Tercer Trimestre  
7  9003582 NOGOYA       NOGOYÁ    N         COMPLETO SEXTO   Tercer Trimestre  
8  9003582 NOGOYA       NOGOYÁ    N         COMPLETO SEXTO   Tercer Trimestre  
9  9003582 NOGOYA       NOGOYÁ    N         COMPLETO SEXTO   Tercer Trimestre  
10 9003582 NOGOYA       NOGOYÁ    N         COMPLETO SEXTO   Tercer Trimestre  
11 9000309 NOGOYA       NOGOYÁ    N         MAÑANA   SEXTO   Tercer Trimestre  
12 9003450 NOGOYA       NOGOYÁ    N         MAÑANA   SEXTO   Tercer Trimestre  
13 9000309 NOGOYA       NOGOYÁ    N         MAÑANA   SEXTO   Tercer Trimestre  
14 9000303 NOGOYA       NOGOYÁ    N         MAÑANA   QUINTO  Tercer Trimestre  
15 9010173 NOGOYA       NOGOYÁ    S         TARDE    QUINTO  Tercer Trimestre  
16 9000303 NOGOYA       NOGOYÁ    N         MAÑANA   SEXTO   Tercer Trimestre  
17 9000309 NOGOYA       NOGOYÁ    N         MAÑANA   QUINTO  Tercer Trimestre  
18 9000303 NOGOYA       NOGOYÁ    N         MAÑANA   SEXTO   Tercer Trimestre  
19 9000309 NOGOYA       NOGOYÁ    N         TARDE    QUINTO  Tercer Trimestre  
20 9005349 NOGOYA       NOGOYÁ    N         TARDE    SEXTO   Tercer Trimestre  
21 9000309 NOGOYA       NOGOYÁ    N         MAÑANA   SEXTO   Tercer Trimestre  
22 9003450 NOGOYA       NOGOYÁ    N         MAÑANA   QUINTO  Tercer Trimestre  
23 9003450 NOGOYA       NOGOYÁ    N         MAÑANA   SEXTO   Tercer Trimestre  
24 9000309 NOGOYA       NOGOYÁ    N         MAÑANA   SEXTO   Tercer Trimestre  
25 9000303 NOGOYA       NOGOYÁ    N         TARDE    SEGUNDO Tercer Trimestre  
26 9005541 NOGOYA       NOGOYÁ    N         MAÑANA   QUINTO  Tercer Trimestre  
27 9005349 NOGOYA       NOGOYÁ    N         TARDE    SEXTO   Tercer Trimestre  
28 9005349 NOGOYA       NOGOYÁ    N         TARDE    SEXTO   Tercer Trimestre  
29 9005349 NOGOYA       NOGOYÁ    N         TARDE    SEXTO   Tercer Trimestre  
30 9005349 NOGOYA       NOGOYÁ    N         TARDE    SEXTO   Tercer Trimestre  
   Documento Asignatura NivelEnsenanza ModEnsenanza AnioLectivo
1   49438965 LENGUA     PRIMARIO       Comun        2023       
2   49565265 LENGUA     PRIMARIO       Comun        2023       
3   49817076 LENGUA     PRIMARIO       Comun        2023       
4   49817076 LENGUA     PRIMARIO       Comun        2023       
5   49817076 LENGUA     PRIMARIO       Comun        2023       
6   49817076 LENGUA     PRIMARIO       Comun        2023       
7   49817076 LENGUA     PRIMARIO       Comun        2023       
8   49817076 LENGUA     PRIMARIO       Comun        2023       
9   49817076 LENGUA     PRIMARIO       Comun        2023       
10  49817076 LENGUA     PRIMARIO       Comun        2023       
11  50383935 LENGUA     PRIMARIO       Comun        2023       
12  50383964 LENGUA     PRIMARIO       Comun        2023       
13  50447567 LENGUA     PRIMARIO       Comun        2023       
14  50588849 LENGUA     PRIMARIO       Comun        2023       
15  50747324 LENGUA     PRIMARIO       Comun        2023       
16  50927788 LENGUA     PRIMARIO       Comun        2023       
17  50927849 LENGUA     PRIMARIO       Comun        2023       
18  51036370 LENGUA     PRIMARIO       Comun        2023       
19  51114734 LENGUA     PRIMARIO       Comun        2023       
20  51114758 LENGUA     PRIMARIO       Comun        2023       
21  51283597 LENGUA     PRIMARIO       Comun        2023       
22  51283614 LENGUA     PRIMARIO       Comun        2023       
23  51283637 LENGUA     PRIMARIO       Comun       

In [55]:
dim(lengua)

[1] 11309    17

In [56]:
lengua_sin_duplicados <- distinct(lengua, Documento, .keep_all = TRUE)

In [57]:
dim(lengua_sin_duplicados)

[1] 2907   17

In [58]:
head(lengua_sin_duplicados,10)

CUE     Departamento Localidad EsPrivada Turno    Curso  PeriodoEvaluatorio
1  9005547 NOGOYA       NOGOYÁ    N         MAÑANA   SEXTO  Tercer Trimestre  
2  9005373 NOGOYA       NOGOYÁ    N         MAÑANA   SEXTO  Tercer Trimestre  
3  9003582 NOGOYA       NOGOYÁ    N         COMPLETO SEXTO  Tercer Trimestre  
4  9000309 NOGOYA       NOGOYÁ    N         MAÑANA   SEXTO  Tercer Trimestre  
5  9003450 NOGOYA       NOGOYÁ    N         MAÑANA   SEXTO  Tercer Trimestre  
6  9000309 NOGOYA       NOGOYÁ    N         MAÑANA   SEXTO  Tercer Trimestre  
7  9000303 NOGOYA       NOGOYÁ    N         MAÑANA   QUINTO Tercer Trimestre  
8  9010173 NOGOYA       NOGOYÁ    S         TARDE    QUINTO Tercer Trimestre  
9  9000303 NOGOYA       NOGOYÁ    N         MAÑANA   SEXTO  Tercer Trimestre  
10 9000309 NOGOYA       NOGOYÁ    N         MAÑANA   QUINTO Tercer Trimestre  
   Documento Asignatura NivelEnsenanza ModEnsenanza AnioLectivo
1  49438965  LENGUA     PRIMARIO       Comun        2023       
2  49565265  LENGUA     PRIMARIO       Comun        2023       
3  49817076  LENGUA     PRIMARIO       Comun        2023       
4  50383935  LENGUA     PRIMARIO       Comun        2023       
5  50383964  LENGUA     PRIMARIO       Comun        2023       
6  50447567  LENGUA     PRIMARIO       Comun        2023       
7  50588849  LENGUA     PRIMARIO       Comun        2023       
8  50747324  LENGUA     PRIMARIO       Comun        2023       
9  50927788  LENGUA     PRIMARIO       Comun        2023       
10 50927849  LENGUA     PRIMARIO       Comun        2023       
   NotasPrimerTPrimario NotasSegundoTPrimario NotasTercerTPrimario Promedio   
1  6                    EPAC                  EPAC                 Desaprobado
2  7                    6                     EPAC                 Desaprobado
3  EPAC                 EPAC                  EPAC                 Desaprobado
4  EPAC                 EPAC                  EPAC                 Desaprobado
5  EPAC                 EPAC                  EPAC                 Desaprobado
6  EPAC                 EPAC                  EPAC                 Desaprobado
7  6                    EPAC                  EPAC                 Desaprobado
8  EPAC                 EPAC                  EPAC                 Desaprobado
9  EPAC                 EPAC                  EPAC                 Desaprobado
10 EPAC                 EPAC                  EPAC                 Desaprobado
   Condicion  
1  DESAPROBADO
2  DESAPROBADO
3  DESAPROBADO
4  DESAPROBADO
5  DESAPROBADO
6  DESAPROBADO
7  DESAPROBADO
8  DESAPROBADO
9  DESAPROBADO
10 DESAPROBADO

In [59]:
table(lengua_sin_duplicados$Curso)


 CUARTO PRIMERO  QUINTO SEGUNDO   SEXTO TERCERO 
    481     476     512     507     413     518 

## Secundaria ##

In [60]:
#filtrar datos y generar nuevo dataset para las escuelas secundarias, nos quedamos solo con las modalidades comun y tecnicas
NOGOYAS <-filter(NOGOYA,  NivelEnsenanza=="SECUNDARIO" & EsMultianio== "N" & ( ModEnsenanza=="Comun"| ModEnsenanza=="Técnica" | ModEnsenanza=="Agrotécnica" | ModEnsenanza=="Cap Tecnica Priv"))

dim(NOGOYAS)
NOGOYAS

[1] 156057     17

X      CUE     Departamento Localidad CP   EsPrivada Turno  Curso      
1      148715 9008040 NOGOYA       NOGOYÁ    3158 N         MAÑANA 1 - B CBC  
2      148716 9008040 NOGOYA       NOGOYÁ    3158 N         MAÑANA 1 - B CBC  
3      148717 9008040 NOGOYA       NOGOYÁ    3158 N         MAÑANA 1 - B CBC  
4      148718 9008040 NOGOYA       NOGOYÁ    3158 N         MAÑANA 1 - B CBC  
5      148719 9008040 NOGOYA       NOGOYÁ    3158 N         MAÑANA 1 - B CBC  
6      148720 9008040 NOGOYA       NOGOYÁ    3158 N         MAÑANA 1 - B CBC  
7      148721 9008040 NOGOYA       NOGOYÁ    3158 N         MAÑANA 1 - B CBC  
8      148722 9008040 NOGOYA       NOGOYÁ    3158 N         MAÑANA 1 - B CBC  
9      148723 9008040 NOGOYA       NOGOYÁ    3158 N         MAÑANA 1 - B CBC  
10     148724 9008040 NOGOYA       NOGOYÁ    3158 N         MAÑANA 1 - B CBC  
11     148725 9008040 NOGOYA       NOGOYÁ    3158 N         MAÑANA 1 - B CBC  
12     148726 9008040 NOGOYA       NOGOYÁ    3158 N         MAÑANA 1 - B CBC  
13     148738 9007683 NOGOYA       NOGOYÁ    3158 N         MAÑANA 5 - A 3322E
14     148739 9007683 NOGOYA       NOGOYÁ    3158 N         MAÑANA 5 - A 3322E
15     148740 9007683 NOGOYA       NOGOYÁ    3158 N         MAÑANA 5 - A 3322E
16     148741 9007683 NOGOYA       NOGOYÁ    3158 N         MAÑANA 5 - A 3322E
17     148742 9007683 NOGOYA       NOGOYÁ    3158 N         MAÑANA 5 - A 3322E
18     148743 9007683 NOGOYA       NOGOYÁ    3158 N         MAÑANA 5 - A 3322E
19     148744 9007683 NOGOYA       NOGOYÁ    3158 N         MAÑANA 5 - A 3322E
20     148745 9007683 NOGOYA       NOGOYÁ    3158 N         MAÑANA 5 - A 3322E
21     148746 9007683 NOGOYA       NOGOYÁ    3158 N         MAÑANA 5 - A 3322E
22     148747 9007683 NOGOYA       NOGOYÁ    3158 N         MAÑANA 5 - A 3322E
23     148748 9007683 NOGOYA       NOGOYÁ    3158 N         MAÑANA 5 - A 3322E
24     148749 9007683 NOGOYA       NOGOYÁ    3158 N         MAÑANA 5 - A 3322E
25     148750 9008040 NOGOYA       NOGOYÁ    3158 N         MAÑANA 1 - B CBC  
26     148751 9008040 NOGOYA       NOGOYÁ    3158 N         MAÑANA 1 - B CBC  
27     148752 9008040 NOGOYA       NOGOYÁ    3158 N         MAÑANA 1 - B CBC  
28     148753 9008040 NOGOYA       NOGOYÁ    3158 N         MAÑANA 1 - B CBC  
29     148754 9008040 NOGOYA       NOGOYÁ    3158 N         MAÑANA 1 - B CBC  
30     148755 9008040 NOGOYA       NOGOYÁ    3158 N         MAÑANA 1 - B CBC  
...    ...    ...     ...          ...       ...  ...       ...    ...        
156028 326592 9007683 NOGOYA       NOGOYÁ    3158 N         MAÑANA 3 - B CBC  
156029 326593 9007683 NOGOYA       NOGOYÁ    3158 N         MAÑANA 3 - B CBC  
156030 326594 9007683 NOGOYA       NOGOYÁ    3158 N         MAÑANA 3 - B CBC  
156031 326595 9007683 NOGOYA       NOGOYÁ    3158 N         MAÑANA 3 - B CBC  
156032 326596 9007683 NOGOYA       NOGOYÁ    3158 N         MAÑANA 3 - B CBC  
156033 326597 9007683 NOGOYA       NOGOYÁ    3158 N         MAÑANA 3 - B CBC  
156034 326598 9007683 NOGOYA       NOGOYÁ    3158 N         MAÑANA 3 - B CBC  
156035 326599 9007683 NOGOYA       NOGOYÁ    3158 N         MAÑANA 3 - B CBC  
156036 326600 9007683 NOGOYA       NOGOYÁ    3158 N         MAÑANA 3 - B CBC  
156037 326601 9007683 NOGOYA       NOGOYÁ    3158 N         MAÑANA 3 - B CBC  
156038 326602 9007683 NOGOYA       NOGOYÁ    3158 N         MAÑANA 3 - B CBC  
156039 326603 9007683 NOGOYA       NOGOYÁ    3158 N         MAÑANA 3 - B CBC  
156040 326604 9007683 NOGOYA       NOGOYÁ    3158 N         MAÑANA 3 - B CBC  
156041 326605 9007683 NOGOYA       NOGOYÁ    3158 N         MAÑANA 3 - B CBC  
156042 326606 9007683 NOGOYA       NOGOYÁ    3158 N         MAÑANA 3 - B CBC  
156043 326607 9007683 NOGOYA       NOGOYÁ    3158 N         MAÑANA 3 - B CBC  
156044 326608 9007683 NOGOYA       NOGOYÁ    3158 N         MAÑANA 3 - B CBC  
156045 326609 9007683 NOGOYA       NOGOYÁ    3158 N         MAÑANA 3 - B CBC  
156046 326610 9007683 NOGOYA       NOGOYÁ    3158 N      

### Aconcidionamiento de la columna Curso ###

In [61]:
table(NOGOYAS$Curso)


               1 - 1 RCBCET                1 - 1 RCBEAT 
                       1857                        2622 
               1 - 2 RCBCET                1 - 2 RCBEAT 
                       1347                        1872 
               1 - 3 RCBCET                1 - 4 RCBCET 
                        918                        1260 
         1 - A 4000Ar 4000A                 1 - A 4000E 
                        101                         105 
                1 - A 4000N                   1 - A CBC 
                        137                        7441 
                 1 - A CBCR                 1 - B 4000E 
                         12                          36 
                1 - B 4000N                   1 - B CBC 
                         80                        4776 
                 1 - B EYAR                 1 - C 4000N 
                        102                         138 
                 1 - C EYAR                  1º - 1 CBC 
                         48   

In [62]:
# me quedo solo con el primer numero representando al curso y excluyo todo lo demas que indica divisiones y detalles innecesarios
NOGOYAS$Curso <- substr(NOGOYAS$Curso, 1, 1)
table(NOGOYAS$Curso)


    1     2     3     4     5     6     7 
31217 29024 23374 30423 23244 16805  1970 

## Acondicionamiento de la columna Asignatura ###

In [63]:
#Pasar a mayúsculas
NOGOYAS$Asignatura <- toupper(NOGOYAS$Asignatura) 
table (NOGOYAS$Asignatura)


                                      ANALISIS MATEMATICO 
                                                       65 
                                          ARQUITECTURA II 
                                                       42 
                                           ARTES VISUALES 
                                                     8127 
                                                  ATENEOS 
                                                        3 
                                                 BIOLOGIA 
                                                     8420 
                                                 BIOLOGÍA 
                                                       32 
                                               CATEQUESIS 
                                                      338 
                                   CEREALES Y OLEAGINOSAS 
                                                      123 
                                     CIENCIA DE LA TIER

### Separacion del dataset por perdiodo evaluatorio ###

In [64]:
table(NOGOYAS$PeriodoEvaluatorio)


          Febrero  Primer Trimestre Segundo Trimestre  Tercer Trimestre 
                4             52957             49679             53417 

In [65]:
PrimerTSecundario<-filter(NOGOYAS,PeriodoEvaluatorio=="Primer Trimestre")
head(PrimerTSecundario)
names(PrimerTSecundario)
PrimerTSecundario<-rename(PrimerTSecundario,NotasPrimerTSecundario=Nota)
dim(PrimerTSecundario)
names(PrimerTSecundario)

X      CUE     Departamento Localidad CP   EsPrivada Turno  Curso
1 148715 9008040 NOGOYA       NOGOYÁ    3158 N         MAÑANA 1    
2 148716 9008040 NOGOYA       NOGOYÁ    3158 N         MAÑANA 1    
3 148717 9008040 NOGOYA       NOGOYÁ    3158 N         MAÑANA 1    
4 148718 9008040 NOGOYA       NOGOYÁ    3158 N         MAÑANA 1    
5 148719 9008040 NOGOYA       NOGOYÁ    3158 N         MAÑANA 1    
6 148720 9008040 NOGOYA       NOGOYÁ    3158 N         MAÑANA 1    
  PeriodoEvaluatorio Documento AnioLectivo Asignatura            Nota
1 Primer Trimestre   50070216  2023        EDUCACION TECNOLOGICA 6   
2 Primer Trimestre   50070216  2023        BIOLOGIA              5   
3 Primer Trimestre   50070216  2023        HISTORIA              5   
4 Primer Trimestre   50070216  2023        MATEMATICA            6   
5 Primer Trimestre   50070216  2023        GEOGRAFIA             7   
6 Primer Trimestre   50070216  2023        LENGUA Y LITERATURA   6   
  NivelEnsenanza Division EsMultianio ModEnsenanza
1 SECUNDARIO     108804   N           Comun       
2 SECUNDARIO     108804   N           Comun       
3 SECUNDARIO     108804   N           Comun       
4 SECUNDARIO     108804   N           Comun       
5 SECUNDARIO     108804   N           Comun       
6 SECUNDARIO     108804   N           Comun

[1] "X"                  "CUE"                "Departamento"      
 [4] "Localidad"          "CP"                 "EsPrivada"         
 [7] "Turno"              "Curso"              "PeriodoEvaluatorio"
[10] "Documento"          "AnioLectivo"        "Asignatura"        
[13] "Nota"               "NivelEnsenanza"     "Division"          
[16] "EsMultianio"        "ModEnsenanza"

[1] 52957    17

[1] "X"                      "CUE"                    "Departamento"          
 [4] "Localidad"              "CP"                     "EsPrivada"             
 [7] "Turno"                  "Curso"                  "PeriodoEvaluatorio"    
[10] "Documento"              "AnioLectivo"            "Asignatura"            
[13] "NotasPrimerTSecundario" "NivelEnsenanza"         "Division"              
[16] "EsMultianio"            "ModEnsenanza"

In [66]:
SegundoTSecundario<-filter(NOGOYAS,PeriodoEvaluatorio=="Segundo Trimestre")
head(SegundoTSecundario)
names(SegundoTSecundario)
SegundoTSecundario<-rename(SegundoTSecundario,NotasSegundoTSecundario=Nota)
dim(SegundoTSecundario)
names(SegundoTSecundario)

X      CUE     Departamento Localidad CP   EsPrivada Turno  Curso
1 149693 9005505 NOGOYA       NOGOYÁ    3162 N         MAÑANA 1    
2 155624 9000306 NOGOYA       NOGOYÁ    3150 N         DOBLE  1    
3 162158 9000306 NOGOYA       NOGOYÁ    3150 N         DOBLE  1    
4 162264 9000306 NOGOYA       NOGOYÁ    3150 N         DOBLE  1    
5 162288 9000306 NOGOYA       NOGOYÁ    3150 N         DOBLE  1    
6 162355 9000306 NOGOYA       NOGOYÁ    3150 N         DOBLE  1    
  PeriodoEvaluatorio Documento AnioLectivo Asignatura       Nota NivelEnsenanza
1 Segundo Trimestre  41753180  2023        MATEMATICA       NULL SECUNDARIO    
2 Segundo Trimestre  50383967  2023        EDUCACION FISICA NULL SECUNDARIO    
3 Segundo Trimestre  50181950  2023        EDUCACION FISICA NULL SECUNDARIO    
4 Segundo Trimestre  49565229  2023        EDUCACION FISICA NULL SECUNDARIO    
5 Segundo Trimestre  50181962  2023        EDUCACION FISICA NULL SECUNDARIO    
6 Segundo Trimestre  49565228  2023        EDUCACION FISICA NULL SECUNDARIO    
  Division EsMultianio ModEnsenanza
1 120721   N           Comun       
2  86805   N           Comun       
3  86805   N           Agrotécnica 
4  86805   N           Agrotécnica 
5  86805   N           Agrotécnica 
6  86805   N           Agrotécnica

[1] "X"                  "CUE"                "Departamento"      
 [4] "Localidad"          "CP"                 "EsPrivada"         
 [7] "Turno"              "Curso"              "PeriodoEvaluatorio"
[10] "Documento"          "AnioLectivo"        "Asignatura"        
[13] "Nota"               "NivelEnsenanza"     "Division"          
[16] "EsMultianio"        "ModEnsenanza"

[1] 49679    17

[1] "X"                       "CUE"                    
 [3] "Departamento"            "Localidad"              
 [5] "CP"                      "EsPrivada"              
 [7] "Turno"                   "Curso"                  
 [9] "PeriodoEvaluatorio"      "Documento"              
[11] "AnioLectivo"             "Asignatura"             
[13] "NotasSegundoTSecundario" "NivelEnsenanza"         
[15] "Division"                "EsMultianio"            
[17] "ModEnsenanza"

In [67]:
TercerTSecundario<-filter(NOGOYAS,PeriodoEvaluatorio=="Tercer Trimestre")
head(TercerTSecundario)
names(TercerTSecundario)
TercerTSecundario<-rename(TercerTSecundario,NotasTercerTSecundario=Nota)
dim(TercerTSecundario)
names(TercerTSecundario)

X      CUE     Departamento Localidad CP   EsPrivada Turno Curso
1 167797 9007386 NOGOYA       NOGOYÁ    3158 N         NOCHE 3    
2 264476 9005349 NOGOYA       NOGOYÁ    3150 N         TARDE 1    
3 264477 9005349 NOGOYA       NOGOYÁ    3150 N         TARDE 1    
4 264478 9005349 NOGOYA       NOGOYÁ    3150 N         TARDE 1    
5 264479 9005349 NOGOYA       NOGOYÁ    3150 N         TARDE 1    
6 264480 9005349 NOGOYA       NOGOYÁ    3150 N         TARDE 1    
  PeriodoEvaluatorio Documento AnioLectivo Asignatura          Nota
1 Tercer Trimestre   41117528  2023        TUTORIAS            10  
2 Tercer Trimestre   49564806  2023        LENGUA Y LITERATURA 7   
3 Tercer Trimestre   49564806  2023        LENGUAS EXTRANJERAS 7   
4 Tercer Trimestre   49564806  2023        ARTES VISUALES      9   
5 Tercer Trimestre   49564806  2023        HISTORIA            8   
6 Tercer Trimestre   49564806  2023        GEOGRAFIA           9   
  NivelEnsenanza Division EsMultianio ModEnsenanza
1 SECUNDARIO     99272    N           Comun       
2 SECUNDARIO     93025    N           Comun       
3 SECUNDARIO     93025    N           Comun       
4 SECUNDARIO     93025    N           Comun       
5 SECUNDARIO     93025    N           Comun       
6 SECUNDARIO     93025    N           Comun

[1] "X"                  "CUE"                "Departamento"      
 [4] "Localidad"          "CP"                 "EsPrivada"         
 [7] "Turno"              "Curso"              "PeriodoEvaluatorio"
[10] "Documento"          "AnioLectivo"        "Asignatura"        
[13] "Nota"               "NivelEnsenanza"     "Division"          
[16] "EsMultianio"        "ModEnsenanza"

[1] 53417    17

[1] "X"                      "CUE"                    "Departamento"          
 [4] "Localidad"              "CP"                     "EsPrivada"             
 [7] "Turno"                  "Curso"                  "PeriodoEvaluatorio"    
[10] "Documento"              "AnioLectivo"            "Asignatura"            
[13] "NotasTercerTSecundario" "NivelEnsenanza"         "Division"              
[16] "EsMultianio"            "ModEnsenanza"

In [68]:
union1Secundario <- merge(x=PrimerTSecundario, y=SegundoTSecundario, by= c("Documento", "Asignatura"))
dim(union1Secundario)

[1] 75419    32

In [69]:
union2Secundario<-merge(x = union1Secundario, y=TercerTSecundario , by = c("Documento", "Asignatura"))
dim(union2Secundario)
head(union2Secundario,1)
names(union2Secundario)

[1] 140829     47

Documento Asignatura        X.x    CUE.x   Departamento.x Localidad.x CP.x
1 20477363  DERECHO COMERCIAL 180289 9005505 NOGOYA         NOGOYÁ      3162
  EsPrivada.x Turno.x Curso.x ... EsPrivada Turno Curso PeriodoEvaluatorio
1 N           NOCHE   3       ... N         NOCHE 3     Tercer Trimestre  
  AnioLectivo NotasTercerTSecundario NivelEnsenanza Division EsMultianio
1 2023        8                      SECUNDARIO     108812   N          
  ModEnsenanza
1 Comun

[1] "Documento"               "Asignatura"             
 [3] "X.x"                     "CUE.x"                  
 [5] "Departamento.x"          "Localidad.x"            
 [7] "CP.x"                    "EsPrivada.x"            
 [9] "Turno.x"                 "Curso.x"                
[11] "PeriodoEvaluatorio.x"    "AnioLectivo.x"          
[13] "NotasPrimerTSecundario"  "NivelEnsenanza.x"       
[15] "Division.x"              "EsMultianio.x"          
[17] "ModEnsenanza.x"          "X.y"                    
[19] "CUE.y"                   "Departamento.y"         
[21] "Localidad.y"             "CP.y"                   
[23] "EsPrivada.y"             "Turno.y"                
[25] "Curso.y"                 "PeriodoEvaluatorio.y"   
[27] "AnioLectivo.y"           "NotasSegundoTSecundario"
[29] "NivelEnsenanza.y"        "Division.y"             
[31] "EsMultianio.y"           "ModEnsenanza.y"         
[33] "X"                       "CUE"                    
[35] "Departamento"            "Localidad"              
[37] "CP"                      "EsPrivada"              
[39] "Turno"                   "Curso"                  
[41] "PeriodoEvaluatorio"      "AnioLectivo"            
[43] "NotasTercerTSecundario"  "NivelEnsenanza"         
[45] "Division"                "EsMultianio"            
[47] "ModEnsenanza"

In [70]:
#Seleccionamos las columnas no repetidas que nos interesan para nuestro analisis
Notas_NOGOYA<-select(union2Secundario, 'CUE', 'Departamento', 'Localidad', 'EsPrivada', 'Turno' , 'Curso' , 'PeriodoEvaluatorio' , 'Documento', 'Asignatura', 'NivelEnsenanza', 'ModEnsenanza', 'AnioLectivo','NotasPrimerTSecundario','NotasSegundoTSecundario', 'NotasTercerTSecundario')
dim(Notas_NOGOYA)
head(Notas_NOGOYA,10)

[1] 140829     15

CUE     Departamento Localidad EsPrivada Turno Curso PeriodoEvaluatorio
1  9005505 NOGOYA       NOGOYÁ    N         NOCHE 3     Tercer Trimestre  
2  9005505 NOGOYA       NOGOYÁ    N         NOCHE 3     Tercer Trimestre  
3  9005505 NOGOYA       NOGOYÁ    N         NOCHE 3     Tercer Trimestre  
4  9005505 NOGOYA       NOGOYÁ    N         NOCHE 3     Tercer Trimestre  
5  9005505 NOGOYA       NOGOYÁ    N         NOCHE 3     Tercer Trimestre  
6  9005505 NOGOYA       NOGOYÁ    N         NOCHE 3     Tercer Trimestre  
7  9005505 NOGOYA       NOGOYÁ    N         NOCHE 3     Tercer Trimestre  
8  9005505 NOGOYA       NOGOYÁ    N         NOCHE 3     Tercer Trimestre  
9  9005505 NOGOYA       NOGOYÁ    N         NOCHE 3     Tercer Trimestre  
10 9005505 NOGOYA       NOGOYÁ    N         NOCHE 3     Tercer Trimestre  
   Documento Asignatura                                NivelEnsenanza
1  20477363  DERECHO COMERCIAL                         SECUNDARIO    
2  20477363  GEOGRAFIA                                 SECUNDARIO    
3  20477363  HISTORIA                                  SECUNDARIO    
4  20477363  LEGISLACION LABORAL Y PRACTICA IMPOSITIVA SECUNDARIO    
5  20477363  LENGUA Y LITERATURA                       SECUNDARIO    
6  20477363  LENGUAS EXTRANJERAS                       SECUNDARIO    
7  20477363  MACROECONOMIA                             SECUNDARIO    
8  20477363  MATEMATICA                                SECUNDARIO    
9  20477363  PSICOLOGIA                                SECUNDARIO    
10 20477363  SISTEMA DE INFORMACION CONTABLE           SECUNDARIO    
   ModEnsenanza AnioLectivo NotasPrimerTSecundario NotasSegundoTSecundario
1  Comun        2023        6                      7                      
2  Comun        2023        8                      7                      
3  Comun        2023        7                      8                      
4  Comun        2023        7                      7                      
5  Comun        2023        6                      7                      
6  Comun        2023        6                      6                      
7  Comun        2023        7                      7                      
8  Comun        2023        8                      8                      
9  Comun        2023        8                      8                      
10 Comun        2023        6                      7                      
   NotasTercerTSecundario
1  8                     
2  7                     
3  8                     
4  7                     
5  7                     
6  6                     
7  7                     
8  8                     
9  8                     
10 8

### Columna Promedio ###

In [71]:
Notas_NOGOYA$Promedio<-round((as.numeric(Notas_NOGOYA$NotasPrimerTSecundario)+as.numeric(Notas_NOGOYA$NotasSegundoTSecundario)+as.numeric(Notas_NOGOYA$NotasTercerTSecundario))/3,2)
head(Notas_NOGOYA,10)

Warning message in eval(expr, envir, enclos):
"NAs introducidos por coerción"
Warning message in eval(expr, envir, enclos):
"NAs introducidos por coerción"
Warning message in eval(expr, envir, enclos):
"NAs introducidos por coerción"


CUE     Departamento Localidad EsPrivada Turno Curso PeriodoEvaluatorio
1  9005505 NOGOYA       NOGOYÁ    N         NOCHE 3     Tercer Trimestre  
2  9005505 NOGOYA       NOGOYÁ    N         NOCHE 3     Tercer Trimestre  
3  9005505 NOGOYA       NOGOYÁ    N         NOCHE 3     Tercer Trimestre  
4  9005505 NOGOYA       NOGOYÁ    N         NOCHE 3     Tercer Trimestre  
5  9005505 NOGOYA       NOGOYÁ    N         NOCHE 3     Tercer Trimestre  
6  9005505 NOGOYA       NOGOYÁ    N         NOCHE 3     Tercer Trimestre  
7  9005505 NOGOYA       NOGOYÁ    N         NOCHE 3     Tercer Trimestre  
8  9005505 NOGOYA       NOGOYÁ    N         NOCHE 3     Tercer Trimestre  
9  9005505 NOGOYA       NOGOYÁ    N         NOCHE 3     Tercer Trimestre  
10 9005505 NOGOYA       NOGOYÁ    N         NOCHE 3     Tercer Trimestre  
   Documento Asignatura                                NivelEnsenanza
1  20477363  DERECHO COMERCIAL                         SECUNDARIO    
2  20477363  GEOGRAFIA                                 SECUNDARIO    
3  20477363  HISTORIA                                  SECUNDARIO    
4  20477363  LEGISLACION LABORAL Y PRACTICA IMPOSITIVA SECUNDARIO    
5  20477363  LENGUA Y LITERATURA                       SECUNDARIO    
6  20477363  LENGUAS EXTRANJERAS                       SECUNDARIO    
7  20477363  MACROECONOMIA                             SECUNDARIO    
8  20477363  MATEMATICA                                SECUNDARIO    
9  20477363  PSICOLOGIA                                SECUNDARIO    
10 20477363  SISTEMA DE INFORMACION CONTABLE           SECUNDARIO    
   ModEnsenanza AnioLectivo NotasPrimerTSecundario NotasSegundoTSecundario
1  Comun        2023        6                      7                      
2  Comun        2023        8                      7                      
3  Comun        2023        7                      8                      
4  Comun        2023        7                      7                      
5  Comun        2023        6                      7                      
6  Comun        2023        6                      6                      
7  Comun        2023        7                      7                      
8  Comun        2023        8                      8                      
9  Comun        2023        8                      8                      
10 Comun        2023        6                      7                      
   NotasTercerTSecundario Promedio
1  8                      7.00    
2  7                      7.33    
3  8                      7.67    
4  7                      7.00    
5  7                      6.67    
6  6                      6.00    
7  7                      7.00    
8  8                      8.00    
9  8                      8.00    
10 8                      7.00

In [72]:

# Convertir la columna NotasTercerTSecundario a tipo numérico
Notas_NOGOYA <- Notas_NOGOYA %>%
  mutate(NotasTercerTSecundario = as.numeric(NotasTercerTSecundario))

# Agregar una nueva columna llamada condicion
Notas_NOGOYA <- Notas_NOGOYA %>%
  mutate(condicion = ifelse(NotasTercerTSecundario >= 6, "APROBADO", "DESAPROBADO"))

# Verificar los primeros registros del dataframe resultante
head(Notas_NOGOYA,30)
tail(Notas_NOGOYA,30)

Warning message:
"There was 1 warning in `mutate()`.
i In argument: `NotasTercerTSecundario = as.numeric(NotasTercerTSecundario)`.
Caused by warning:
! NAs introducidos por coerción"


CUE     Departamento Localidad EsPrivada Turno Curso PeriodoEvaluatorio
1  9005505 NOGOYA       NOGOYÁ    N         NOCHE 3     Tercer Trimestre  
2  9005505 NOGOYA       NOGOYÁ    N         NOCHE 3     Tercer Trimestre  
3  9005505 NOGOYA       NOGOYÁ    N         NOCHE 3     Tercer Trimestre  
4  9005505 NOGOYA       NOGOYÁ    N         NOCHE 3     Tercer Trimestre  
5  9005505 NOGOYA       NOGOYÁ    N         NOCHE 3     Tercer Trimestre  
6  9005505 NOGOYA       NOGOYÁ    N         NOCHE 3     Tercer Trimestre  
7  9005505 NOGOYA       NOGOYÁ    N         NOCHE 3     Tercer Trimestre  
8  9005505 NOGOYA       NOGOYÁ    N         NOCHE 3     Tercer Trimestre  
9  9005505 NOGOYA       NOGOYÁ    N         NOCHE 3     Tercer Trimestre  
10 9005505 NOGOYA       NOGOYÁ    N         NOCHE 3     Tercer Trimestre  
11 9005505 NOGOYA       NOGOYÁ    N         NOCHE 3     Tercer Trimestre  
12 9005505 NOGOYA       NOGOYÁ    N         NOCHE 3     Tercer Trimestre  
13 9005505 NOGOYA       NOGOYÁ    N         NOCHE 3     Tercer Trimestre  
14 9003453 NOGOYA       NOGOYÁ    S         NOCHE 1     Tercer Trimestre  
15 9003453 NOGOYA       NOGOYÁ    S         NOCHE 1     Tercer Trimestre  
16 9003453 NOGOYA       NOGOYÁ    S         NOCHE 1     Tercer Trimestre  
17 9003453 NOGOYA       NOGOYÁ    S         NOCHE 1     Tercer Trimestre  
18 9003453 NOGOYA       NOGOYÁ    S         NOCHE 1     Tercer Trimestre  
19 9003453 NOGOYA       NOGOYÁ    S         NOCHE 1     Tercer Trimestre  
20 9003453 NOGOYA       NOGOYÁ    S         NOCHE 1     Tercer Trimestre  
21 9003453 NOGOYA       NOGOYÁ    S         NOCHE 1     Tercer Trimestre  
22 9003453 NOGOYA       NOGOYÁ    S         NOCHE 1     Tercer Trimestre  
23 9003453 NOGOYA       NOGOYÁ    S         NOCHE 1     Tercer Trimestre  
24 9003453 NOGOYA       NOGOYÁ    S         NOCHE 1     Tercer Trimestre  
25 9003453 NOGOYA       NOGOYÁ    S         NOCHE 1     Tercer Trimestre  
26 9007452 NOGOYA       NOGOYÁ    N         NOCHE 6     Tercer Trimestre  
27 9007452 NOGOYA       NOGOYÁ    N         NOCHE 6     Tercer Trimestre  
28 9007452 NOGOYA       NOGOYÁ    N         NOCHE 6     Tercer Trimestre  
29 9007452 NOGOYA       NOGOYÁ    N         NOCHE 6     Tercer Trimestre  
30 9007452 NOGOYA       NOGOYÁ    N         NOCHE 6     Tercer Trimestre  
   Documento Asignatura                                     NivelEnsenanza
1  20477363  DERECHO COMERCIAL                              SECUNDARIO    
2  20477363  GEOGRAFIA                                      SECUNDARIO    
3  20477363  HISTORIA                                       SECUNDARIO    
4  20477363  LEGISLACION LABORAL Y PRACTICA IMPOSITIVA      SECUNDARIO    
5  20477363  LENGUA Y LITERATURA                            SECUNDARIO    
6  20477363  LENGUAS EXTRANJERAS                            SECUNDARIO    
7  20477363  MACROECONOMIA                                  SECUNDARIO    
8  20477363  MATEMATICA                                     SECUNDARIO    
9  20477363  PSICOLOGIA                                     SECUNDARIO    
10 20477363  SISTEMA DE INFORMACION CONTABLE                SECUNDARIO    
11 20477363  TECNOLOGIA DE LA INFORMACION Y LA COMUNICACION SECUNDARIO    
12 20477363  TEORIA Y GESTION DE LAS ORGANIZACIONES II      SECUNDARIO    
13 20477363  TUTORIAS                                       SECUNDARIO    
14 22265678  BIOLOGIA                                       SECUNDARIO    
15 22265678  ECONOMIA                                       SECUNDARIO    
16 22265678  EDUCACION TECNOLOGICA                          SECUNDARIO    
17 22265678  FISICA                                         SECUNDARIO    
18 22265678  FORMACION ETICA Y CIUDADANA                    SECUNDARIO    
19 22265678  GEOGRAFIA                                      SECUNDARIO    
20 22265678  HISTORIA                                       SECUNDARIO    
21 22265678  INTRODUCCION A LA ADMINISTRACION               SECUNDARIO    
22 22265678  LENGUA Y LITERA

CUE     Departamento Localidad EsPrivada Turno  Curso PeriodoEvaluatorio
140800 9003441 NOGOYA       NOGOYÁ    N         MAÑANA 1     Tercer Trimestre  
140801 9003441 NOGOYA       NOGOYÁ    N         MAÑANA 1     Tercer Trimestre  
140802 9003441 NOGOYA       NOGOYÁ    N         MAÑANA 1     Tercer Trimestre  
140803 9003441 NOGOYA       NOGOYÁ    N         MAÑANA 1     Tercer Trimestre  
140804 9003441 NOGOYA       NOGOYÁ    N         MAÑANA 1     Tercer Trimestre  
140805 9003441 NOGOYA       NOGOYÁ    N         MAÑANA 1     Tercer Trimestre  
140806 9003441 NOGOYA       NOGOYÁ    N         MAÑANA 1     Tercer Trimestre  
140807 9003441 NOGOYA       NOGOYÁ    N         MAÑANA 1     Tercer Trimestre  
140808 9003441 NOGOYA       NOGOYÁ    N         MAÑANA 1     Tercer Trimestre  
140809 9003441 NOGOYA       NOGOYÁ    N         MAÑANA 1     Tercer Trimestre  
140810 9003441 NOGOYA       NOGOYÁ    N         MAÑANA 1     Tercer Trimestre  
140811 9003441 NOGOYA       NOGOYÁ    N         MAÑANA 1     Tercer Trimestre  
140812 9003441 NOGOYA       NOGOYÁ    N         MAÑANA 1     Tercer Trimestre  
140813 9003441 NOGOYA       NOGOYÁ    N         MAÑANA 1     Tercer Trimestre  
140814 9003441 NOGOYA       NOGOYÁ    N         MAÑANA 1     Tercer Trimestre  
140815 9003441 NOGOYA       NOGOYÁ    N         MAÑANA 1     Tercer Trimestre  
140816 9000330 NOGOYA       NOGOYÁ    S         MAÑANA 6     Tercer Trimestre  
140817 9000330 NOGOYA       NOGOYÁ    S         MAÑANA 6     Tercer Trimestre  
140818 9000330 NOGOYA       NOGOYÁ    S         MAÑANA 6     Tercer Trimestre  
140819 9000330 NOGOYA       NOGOYÁ    S         MAÑANA 6     Tercer Trimestre  
140820 9000330 NOGOYA       NOGOYÁ    S         MAÑANA 6     Tercer Trimestre  
140821 9000330 NOGOYA       NOGOYÁ    S         MAÑANA 6     Tercer Trimestre  
140822 9000330 NOGOYA       NOGOYÁ    S         MAÑANA 6     Tercer Trimestre  
140823 9000330 NOGOYA       NOGOYÁ    S         MAÑANA 6     Tercer Trimestre  
140824 9000330 NOGOYA       NOGOYÁ    S         MAÑANA 6     Tercer Trimestre  
140825 9000330 NOGOYA       NOGOYÁ    S         MAÑANA 6     Tercer Trimestre  
140826 9000330 NOGOYA       NOGOYÁ    S         MAÑANA 6     Tercer Trimestre  
140827 9000330 NOGOYA       NOGOYÁ    S         MAÑANA 6     Tercer Trimestre  
140828 9000330 NOGOYA       NOGOYÁ    S         MAÑANA 6     Tercer Trimestre  
140829 9000330 NOGOYA       NOGOYÁ    S         MAÑANA 6     Tercer Trimestre  
       Documento Asignatura                                NivelEnsenanza
140800 95830082  FORMACION ETICA Y CIUDADANA               SECUNDARIO    
140801 95830082  FORMACION ETICA Y CIUDADANA               SECUNDARIO    
140802 95830082  FORMACION ETICA Y CIUDADANA               SECUNDARIO    
140803 95830082  FORMACION ETICA Y CIUDADANA               SECUNDARIO    
140804 95830082  FORMACION ETICA Y CIUDADANA               SECUNDARIO    
140805 95830082  FORMACION ETICA Y CIUDADANA               SECUNDARIO    
140806 95830082  FORMACION ETICA Y CIUDADANA               SECUNDARIO    
140807 95830082  FORMACION ETICA Y CIUDADANA               SECUNDARIO    
140808 95830082  LENGUA Y LITERATURA                       SECUNDARIO    
140809 95830082  LENGUA Y LITERATURA                       SECUNDARIO    
140810 95830082  LENGUA Y LITERATURA                       SECUNDARIO    
140811 95830082  LENGUA Y LITERATURA                       SECUNDARIO    
140812 95830082  LENGUA Y LITERATURA                       SECUNDARIO    
140813 95830082  LENGUA Y LITERATURA                       SECUNDARIO    
140814 95830082  LENGUA Y LITERATURA                       SECUNDARIO    
140815 95830082  LENGUA Y LITERATURA                       SECUNDARIO    
140816 96237081  DERECHO COMERCIAL                         SECUNDARIO    
140817 96237081  EDUCACION FISICA                          SECUNDARIO    
140818 96237081  FORMACION ETICA Y CIUDADANA               SECUNDARIO    
140819 96237081  HISTORIA                      

In [73]:
table(Notas_NOGOYA$Curso)


    1     2     3     4     5     6     7 
34866 31528 21980 26715 14941  9882   917 

In [74]:
#Cambio de nombre de los cursos de numero a letras
library('stringr')
Notas_NOGOYA$Curso <- str_replace (Notas_NOGOYA$Curso, "1" , "PRIMERO")
Notas_NOGOYA$Curso <- str_replace (Notas_NOGOYA$Curso, "2" , "SEGUNDO")
Notas_NOGOYA$Curso <- str_replace (Notas_NOGOYA$Curso, "3" , "TERCERO")
Notas_NOGOYA$Curso <- str_replace (Notas_NOGOYA$Curso, "4" , "CUARTO")
Notas_NOGOYA$Curso <- str_replace (Notas_NOGOYA$Curso, "5" , "QUINTO")
Notas_NOGOYA$Curso <- str_replace (Notas_NOGOYA$Curso, "6" , "SEXTO")
Notas_NOGOYA$Curso <- str_replace (Notas_NOGOYA$Curso, "7" , "SEPTIMO")

In [75]:
table (Notas_NOGOYA$Curso)


 CUARTO PRIMERO  QUINTO SEGUNDO SEPTIMO   SEXTO TERCERO 
  26715   34866   14941   31528     917    9882   21980 

In [76]:
table (Notas_NOGOYA$Turno)


COMPLETO   DIURNO    DOBLE   MAÑANA    NOCHE ROTATIVO    TARDE 
    2114     1911     6442    97639     2506       16    30201 

In [77]:
#Quito el turno noche debido a que no deberia estar porque solo contemplamos escuelas comunes y tecnicas
Notas_NOGOYA <- Notas_NOGOYA %>%
  filter(Turno != 'NOCHE')

In [78]:
table (Notas_NOGOYA$Turno)


COMPLETO   DIURNO    DOBLE   MAÑANA ROTATIVO    TARDE 
    2114     1911     6442    97639       16    30201 

In [79]:
#Elimino las entradas con promedio NA
Notas_NOGOYA_FILTRADO <- filter(Notas_NOGOYA, !is.na(Promedio))


### Materia troncal para determinar el numero de alumnos ###

In [80]:
#Elijo matematica
matematica<-Notas_NOGOYA_FILTRADO %>% group_by(CUE,Asignatura) %>%  filter(Asignatura=="MATEMATICA") 
matematica

CUE     Departamento Localidad EsPrivada Turno  Curso  
1     9005505 NOGOYA       NOGOYÁ    N         MAÑANA PRIMERO
2     9005349 NOGOYA       NOGOYÁ    N         TARDE  TERCERO
3     9005505 NOGOYA       NOGOYÁ    N         MAÑANA PRIMERO
4     9009117 NOGOYA       NOGOYÁ    S         MAÑANA SEXTO  
5     9008040 NOGOYA       NOGOYÁ    N         MAÑANA SEXTO  
6     9008040 NOGOYA       NOGOYÁ    N         MAÑANA SEXTO  
7     9008040 NOGOYA       NOGOYÁ    N         MAÑANA SEXTO  
8     9008040 NOGOYA       NOGOYÁ    N         MAÑANA SEXTO  
9     9008040 NOGOYA       NOGOYÁ    N         MAÑANA SEXTO  
10    9008040 NOGOYA       NOGOYÁ    N         MAÑANA SEXTO  
11    9008040 NOGOYA       NOGOYÁ    N         MAÑANA SEXTO  
12    9008040 NOGOYA       NOGOYÁ    N         MAÑANA SEXTO  
13    9007680 NOGOYA       NOGOYÁ    N         TARDE  SEXTO  
14    9007680 NOGOYA       NOGOYÁ    N         TARDE  SEXTO  
15    9007680 NOGOYA       NOGOYÁ    N         TARDE  SEXTO  
16    9007680 NOGOYA       NOGOYÁ    N         TARDE  SEXTO  
17    9007680 NOGOYA       NOGOYÁ    N         TARDE  SEXTO  
18    9007680 NOGOYA       NOGOYÁ    N         TARDE  SEXTO  
19    9007680 NOGOYA       NOGOYÁ    N         TARDE  SEXTO  
20    9007680 NOGOYA       NOGOYÁ    N         TARDE  SEXTO  
21    9007680 NOGOYA       NOGOYÁ    N         TARDE  SEXTO  
22    9007680 NOGOYA       NOGOYÁ    N         TARDE  SEXTO  
23    9007680 NOGOYA       NOGOYÁ    N         TARDE  SEXTO  
24    9007680 NOGOYA       NOGOYÁ    N         TARDE  SEXTO  
25    9007680 NOGOYA       NOGOYÁ    N         TARDE  SEXTO  
26    9007680 NOGOYA       NOGOYÁ    N         TARDE  SEXTO  
27    9007680 NOGOYA       NOGOYÁ    N         TARDE  SEXTO  
28    9007680 NOGOYA       NOGOYÁ    N         TARDE  SEXTO  
29    9005349 NOGOYA       NOGOYÁ    N         MAÑANA SEXTO  
30    9007770 NOGOYA       NOGOYÁ    N         MAÑANA SEXTO  
...   ...     ...          ...       ...       ...    ...    
10709 9005349 NOGOYA       NOGOYÁ    N         MAÑANA PRIMERO
10710 9005349 NOGOYA       NOGOYÁ    N         MAÑANA PRIMERO
10711 9005349 NOGOYA       NOGOYÁ    N         MAÑANA PRIMERO
10712 9005349 NOGOYA       NOGOYÁ    N         MAÑANA PRIMERO
10713 9005349 NOGOYA       NOGOYÁ    N         MAÑANA PRIMERO
10714 9005349 NOGOYA       NOGOYÁ    N         MAÑANA PRIMERO
10715 9005349 NOGOYA       NOGOYÁ    N         MAÑANA PRIMERO
10716 9007680 NOGOYA       NOGOYÁ    N         MAÑANA PRIMERO
10717 9000306 NOGOYA       NOGOYÁ    N         DOBLE  PRIMERO
10718 9000306 NOGOYA       NOGOYÁ    N         DOBLE  PRIMERO
10719 9000306 NOGOYA       NOGOYÁ    N         DOBLE  PRIMERO
10720 9000306 NOGOYA       NOGOYÁ    N         DOBLE  PRIMERO
10721 9000306 NOGOYA       NOGOYÁ    N         DOBLE  PRIMERO
10722 9000306 NOGOYA       NOGOYÁ    N         DOBLE  PRIMERO
10723 9000306 NOGOYA       NOGOYÁ    N         DOBLE  PRIMERO
10724 9000306 NOGOYA       NOGOYÁ    N         DOBLE  PRIMERO
10725 9003441 NOGOYA       NOGOYÁ    N         MAÑANA PRIMERO
10726 9007452 NOGOYA       NOGOYÁ    N         MAÑANA PRIMERO
10727 9007452 NOGOYA       NOGOYÁ    N         MAÑANA PRIMERO
10728 9007452 NOGOYA       NOGOYÁ    N         MAÑANA PRIMERO
10729 9007452 NOGOYA       NOGOYÁ    N         MAÑANA PRIMERO
10730 9007452 NOGOYA       NOGOYÁ    N         MAÑANA PRIMERO
10731 9007452 NOGOYA       NOGOYÁ    N         MAÑANA PRIMERO
10732 9007452 NOGOYA       NOGOYÁ    N         MAÑANA PRIMERO
10733 9007452 NOGOYA       NOGOYÁ    N         MAÑANA PRIMERO
10734 9000306 NOGOYA       NOGOYÁ    N         DOBLE  SEGUNDO
10735 9002298 NOGOYA       NOGOYÁ    N         MAÑANA QUINTO 
10736 9007827 NOGOYA       NOGOYÁ    N         DIURNO SEXTO  
10737 9007827 NOGOYA       NOGOYÁ    N         DIURNO CUARTO 
10738 9000330 NOGOYA       NOGOYÁ    S         MAÑANA SEXTO  
      PeriodoEvaluatorio Documento Asignatura NivelEnsenanza ModEnsenanza
1     Tercer Trimestre   41753180  MATEMATICA SECUNDARIO     Comun       
2     Tercer T

In [81]:
head (matematica)

CUE     Departamento Localidad EsPrivada Turno  Curso   PeriodoEvaluatorio
1 9005505 NOGOYA       NOGOYÁ    N         MAÑANA PRIMERO Tercer Trimestre  
2 9005349 NOGOYA       NOGOYÁ    N         TARDE  TERCERO Tercer Trimestre  
3 9005505 NOGOYA       NOGOYÁ    N         MAÑANA PRIMERO Tercer Trimestre  
4 9009117 NOGOYA       NOGOYÁ    S         MAÑANA SEXTO   Tercer Trimestre  
5 9008040 NOGOYA       NOGOYÁ    N         MAÑANA SEXTO   Tercer Trimestre  
6 9008040 NOGOYA       NOGOYÁ    N         MAÑANA SEXTO   Tercer Trimestre  
  Documento Asignatura NivelEnsenanza ModEnsenanza AnioLectivo
1 41753180  MATEMATICA SECUNDARIO     Comun        2023       
2 43630498  MATEMATICA SECUNDARIO     Comun        2023       
3 43630662  MATEMATICA SECUNDARIO     Comun        2023       
4 44166361  MATEMATICA SECUNDARIO     Comun        2023       
5 44439336  MATEMATICA SECUNDARIO     Técnica      2023       
6 44439336  MATEMATICA SECUNDARIO     Comun        2023       
  NotasPrimerTSecundario NotasSegundoTSecundario NotasTercerTSecundario
1 6                      6                        6                    
2 8                      1                        1                    
3 9                      9                        9                    
4 10                     10                      10                    
5 5                      3                        4                    
6 5                      3                        4                    
  Promedio condicion  
1  6.00    APROBADO   
2  3.33    DESAPROBADO
3  9.00    APROBADO   
4 10.00    APROBADO   
5  4.00    DESAPROBADO
6  4.00    DESAPROBADO

In [82]:
#quito los duplicados mediante la columna documento
matematica_sin_duplicados <- distinct(matematica, Documento, .keep_all = TRUE)

In [83]:
nrow(matematica)

[1] 10738

In [84]:
nrow(matematica_sin_duplicados)

[1] 2497

In [85]:
matematica_sin_duplicados

CUE     Departamento Localidad EsPrivada Turno    Curso  
1    9005505 NOGOYA       NOGOYÁ    N         MAÑANA   PRIMERO
2    9005349 NOGOYA       NOGOYÁ    N         TARDE    TERCERO
3    9005505 NOGOYA       NOGOYÁ    N         MAÑANA   PRIMERO
4    9009117 NOGOYA       NOGOYÁ    S         MAÑANA   SEXTO  
5    9008040 NOGOYA       NOGOYÁ    N         MAÑANA   SEXTO  
6    9007680 NOGOYA       NOGOYÁ    N         TARDE    SEXTO  
7    9007680 NOGOYA       NOGOYÁ    N         TARDE    SEXTO  
8    9005349 NOGOYA       NOGOYÁ    N         MAÑANA   SEXTO  
9    9007770 NOGOYA       NOGOYÁ    N         MAÑANA   SEXTO  
10   9005349 NOGOYA       NOGOYÁ    N         MAÑANA   CUARTO 
11   9008061 NOGOYA       NOGOYÁ    N         MAÑANA   QUINTO 
12   9007680 NOGOYA       NOGOYÁ    N         TARDE    SEXTO  
13   9007683 NOGOYA       NOGOYÁ    N         MAÑANA   SEXTO  
14   9007683 NOGOYA       NOGOYÁ    N         MAÑANA   SEXTO  
15   9007683 NOGOYA       NOGOYÁ    N         MAÑANA   CUARTO 
16   9007683 NOGOYA       NOGOYÁ    N         MAÑANA   CUARTO 
17   9007827 NOGOYA       NOGOYÁ    N         DIURNO   QUINTO 
18   9007680 NOGOYA       NOGOYÁ    N         TARDE    SEXTO  
19   9007683 NOGOYA       NOGOYÁ    N         MAÑANA   SEXTO  
20   9007680 NOGOYA       NOGOYÁ    N         TARDE    SEXTO  
21   9005349 NOGOYA       NOGOYÁ    N         TARDE    TERCERO
22   9005349 NOGOYA       NOGOYÁ    N         MAÑANA   SEXTO  
23   9002298 NOGOYA       NOGOYÁ    N         COMPLETO SEPTIMO
24   9005550 NOGOYA       NOGOYÁ    N         DOBLE    SEPTIMO
25   9008061 NOGOYA       NOGOYÁ    N         MAÑANA   SEXTO  
26   9000306 NOGOYA       NOGOYÁ    N         DOBLE    SEPTIMO
27   9003462 NOGOYA       NOGOYÁ    N         MAÑANA   QUINTO 
28   9002298 NOGOYA       NOGOYÁ    N         COMPLETO SEPTIMO
29   9005361 NOGOYA       NOGOYÁ    S         MAÑANA   QUINTO 
30   9008040 NOGOYA       NOGOYÁ    N         MAÑANA   SEXTO  
...  ...     ...          ...       ...       ...      ...    
2468 9005349 NOGOYA       NOGOYÁ    N         MAÑANA   PRIMERO
2469 9003462 NOGOYA       NOGOYÁ    N         TARDE    PRIMERO
2470 9003441 NOGOYA       NOGOYÁ    N         MAÑANA   PRIMERO
2471 9003462 NOGOYA       NOGOYÁ    N         TARDE    PRIMERO
2472 9003462 NOGOYA       NOGOYÁ    N         TARDE    PRIMERO
2473 9005349 NOGOYA       NOGOYÁ    N         MAÑANA   PRIMERO
2474 9010467 NOGOYA       NOGOYÁ    S         MAÑANA   PRIMERO
2475 9003441 NOGOYA       NOGOYÁ    N         MAÑANA   PRIMERO
2476 9002298 NOGOYA       NOGOYÁ    N         COMPLETO PRIMERO
2477 9005550 NOGOYA       NOGOYÁ    N         DOBLE    PRIMERO
2478 9008040 NOGOYA       NOGOYÁ    N         MAÑANA   PRIMERO
2479 9000306 NOGOYA       NOGOYÁ    N         DOBLE    PRIMERO
2480 9003462 NOGOYA       NOGOYÁ    N         TARDE    PRIMERO
2481 9005505 NOGOYA       NOGOYÁ    N         MAÑANA   PRIMERO
2482 9003441 NOGOYA       NOGOYÁ    N         MAÑANA   PRIMERO
2483 9007680 NOGOYA       NOGOYÁ    N         MAÑANA   PRIMERO
2484 9005349 NOGOYA       NOGOYÁ    N         MAÑANA   PRIMERO
2485 9010467 NOGOYA       NOGOYÁ    S         MAÑANA   PRIMERO
2486 9005349 NOGOYA       NOGOYÁ    N         TARDE    PRIMERO
2487 9007683 NOGOYA       NOGOYÁ    N         MAÑANA   PRIMERO
2488 9005349 NOGOYA       NOGOYÁ    N         MAÑANA   PRIMERO
2489 9007680 NOGOYA       NOGOYÁ    N         MAÑANA   PRIMERO
2490 9000306 NOGOYA       NOGOYÁ    N         DOBLE    PRIMERO
2491 9003441 NOGOYA       NOGOYÁ    N         MAÑANA   PRIMERO
2492 9007452 NOGOYA       NOGOYÁ    N         MAÑANA   PRIMERO
2493 9000306 NOGOYA       NOGOYÁ    N         DOBLE    SEGUNDO
2494 9002298 NOGOYA       NOGOYÁ    N         MAÑANA   QUINTO 
2495 9007827 NOGOYA       NOGOYÁ    N         DIURNO   SEXTO  
2496 9007827 NOGOYA       NOGOYÁ    N         DIURNO   CUARTO 
2497 9000330 NOGOYA       NOGOYÁ    S         MAÑANA   SEXTO  
     PeriodoEvaluatorio Documento Asignatura NivelEnsenanza ModEnsenanza
1    Tercer Trimestre   41

In [86]:
table(matematica_sin_duplicados$Curso)


 CUARTO PRIMERO  QUINTO SEGUNDO SEPTIMO   SEXTO TERCERO 
    475     462     388     469      37     267     399 

In [87]:
# Verificar cuántos NAs hay en cada columna
colSums(is.na(Primaria_filtrado))


CUE          Departamento             Localidad 
                    0                     0                     0 
            EsPrivada                 Turno                 Curso 
                    0                     0                     0 
   PeriodoEvaluatorio             Documento            Asignatura 
                    0                     0                     0 
       NivelEnsenanza          ModEnsenanza           AnioLectivo 
                    0                     0                     0 
 NotasPrimerTPrimario NotasSegundoTPrimario  NotasTercerTPrimario 
                    0                     0                     0 
             Promedio             Condicion 
                    0                     0

### Guardamos los datasets de primaria y secundaria ###

In [88]:
library("writexl")

write_xlsx (Notas_NOGOYA_FILTRADO, "C:/Users/guill/OneDrive/Escritorio/NOGOYAS.xlsx")

In [89]:
write_xlsx (Primaria_filtrado, "C:/Users/guill/OneDrive/Escritorio/NOGOYAP.xlsx")

In [90]:
colSums(is.na(Notas_NOGOYA_FILTRADO))


CUE            Departamento               Localidad 
                      0                       0                       0 
              EsPrivada                   Turno                   Curso 
                      0                       0                       0 
     PeriodoEvaluatorio               Documento              Asignatura 
                      0                       0                       0 
         NivelEnsenanza            ModEnsenanza             AnioLectivo 
                      0                       0                       0 
 NotasPrimerTSecundario NotasSegundoTSecundario  NotasTercerTSecundario 
                      0                       0                       0 
               Promedio               condicion 
                      0                       0